### ISSUE TITLE
.prop() documentation has incorrectly placed parenthesis

### ISSUE THREAD

**Issue by james1293** [jquery/api.jquery.com#1003]
[Line 89 ](https://github.com/jquery/api.jquery.com/blob/master/entries/prop.xml#L89) has a parenthesis too early.
Here are lines 86 through 89:
```
 $( "p" ).html(
    ".attr( \"checked\" ): <b>" + $input.attr( "checked" ) + "</b><br>" +
    ".prop( \"checked\" ): <b>" + $input.prop( "checked" ) + "</b><br>" +
    ".is( \":checked\" ): <b>" + $input.is( ":checked" ) ) + "</b>";
```
Line 89 should be
` ".is( \":checked\" ): <b>" + $input.is( ":checked" )  + "</b>");`
so that the `+ "</b>"` is in the .html() command.

**Comment by AurelioDeRosa** [comment]
I confirm the issue.
