### ISSUE TITLE
Surprising callbacks.lock() behavior vs what is documented about it

### ISSUE THREAD

**Issue by callaingit** [jquery/api.jquery.com#1013]
callbacks.lock() seems to behave differently than what is documented at https://api.jquery.com/callbacks.lock/ in more recent versions of jQuery

Specifically, the second example does produce what it says it should produce, but not in more recent jQuery versions.

With jQuery 1.9.1 and 2.1.3 for example, the output is

foo: hello
foo: hello
bar: hello

But in version 2.2.0 and 3.1.1, I am getting this output

foo: hello
foo: hello
foo: silentArgument
foo: silentArgument
bar: silentArgument
foo: youHadMeAtHello
foo: youHadMeAtHello
bar: youHadMeAtHello

I am not sure if it is the documentation that is outdated and the lock() function has change behavior over time or if there is a bug in the versions of jQuery not producing the expected outout.

P.S. I ran the example code in IE 11

**Comment by AurelioDeRosa** [comment]
This seems related to https://github.com/jquery/jquery/commit/32bf9178cace8c52a31c468a28adde9a4fdc4671. So, I think there has been a change in the API.

**Comment by dmethvin** [comment]
@AurelioDeRosa it looks like @gibson042 intended that it be put into 3.0 but it made its way into 2.2.0 as well. That was the release where we had to back-port a ton of stuff from the pre-3.0 fork and a few unintended things got in there.

It seems like we should have the examples from the docs in the unit tests to prevent unintended divergence.  The Callbacks interface is something we only use a small part of and in a very particular way, and I've never used it directly in any jQuery code I've ever written outside the library.

**Comment by gibson042** [comment]
Turns out this is a code issue, not a docs issue. Moving to https://github.com/jquery/jquery/issues/3469 .
