### ISSUE TITLE
Contradiction between show and css documentation about !important behaviour

### ISSUE THREAD

**Issue by eironman** [jquery/api.jquery.com#1014]
In page http://api.jquery.com/show/ there is this note:

Note: If using !important in your styles, such as  display: none !important, it is necessary to override the style using .css( "display", "block !important") should you wish for .show() to function correctly.

Whereas in http://api.jquery.com/css/ we have this note:

Note: .css() ignores !important declarations. So, the statement $( "p" ).css( "color", "red !important" ) does not turn the color of all paragraphs in the page to red. It's strongly advised to use classes instead; otherwise use a jQuery plugin.

**Comment by AurelioDeRosa** [comment]
Good point. Do you want to submit a PR for this?

**Comment by eironman** [comment]
Ah, ok, I'll do that, thanks
