### ISSUE TITLE
$(window).height incorrect for chrome mobile with address bar hiding

### ISSUE THREAD

**Issue by al3x-huang** [jquery/api.jquery.com#1024]
**Background**
On Android chrome, the address bar is hidden whenever the user scrolls down and reappears when the user scrolls back up.

**Issue**
Using $(window).height always returns the same height as when the address bar is showing even though a resize event is triggered.

**Workaround**
I used window.innerHeight instead, which produces the correct, updated height when the resizing event occurs due to the address bar being hidden/shown

**Versions of software**
* Chrome mobile application version: 56.0.2924.87
* Jquery Version: 3.0.0

**Comment by AurelioDeRosa** [comment]
This, if confirmed, is an issue of jQuery itself not the documentation. Please, report it in the correct repository (https://github.com/jquery/jquery). I'm closing this issue.
