### ISSUE TITLE
When using the click() function when in use strict and IE throws an error

### ISSUE THREAD

**Issue by ravenboilinux** [jquery/api.jquery.com#1029]
When you want to programmable click a button you get this error in IE: 
Accessing the 'caller' property of a function or arguments object is not allowed in strict mode

This only happens when you are use strict mode.

**Comment by mgol** [comment]
This is a repo for the API site (https://api.jquery.com/), not jQuery (the jQuery one is at https://github.com/jquery/jquery).

Note, though, that this report doesn't contain enough information for us. We'd need a test case on https://jsfiddle.net or https://jsbin.com.

**Comment by ravenboilinux** [comment]
Sorry thank you
