### ISSUE TITLE
Note in the dimension module methods that some browsers return floats instead of integers

### ISSUE THREAD

**Issue by mikesherov** [jquery/api.jquery.com#103]
As noted in http://bugs.jquery.com/ticket/11401:

> Agreed. Some of the differences in browsers concerning decimal point values should be respected for the sake of animations, if nothing else. We should not hide these.

**Comment by arthurvr** [comment]
This was fixed in https://github.com/jquery/api.jquery.com/commit/2123d42a43f5bb46b7564a81184cd224d7fb4b31, seems like GitHub didn't auto-close.
