### ISSUE TITLE
Document jQuery.each to accept array-likes

### ISSUE THREAD

**Issue by mgol** [jquery/api.jquery.com#1032]
#473 added a note to `jQuery.each` documentation about array-likes but it's not enough. We have an ArrayLikeObject type and we should use it directly in the function signature definition.

**Comment by mgol** [comment]
Thanks for your recent work on this repo, @AurelioDeRosa! 👏

**Comment by AurelioDeRosa** [comment]
It was much overdue. I'm actually really sorry and I feel quite bad for the long silent period.
