### ISSUE TITLE
jQuery.isFunction: ambiguous criteria

### ISSUE THREAD

**Issue by akihikodaki** [jquery/api.jquery.com#1034]
See also https://github.com/jquery/jquery/issues/3600.

The description says:
> Determine if the argument passed is a JavaScript function object.

https://github.com/jquery/api.jquery.com/blob/d622e1244802cd55670265698f0d66383e3dedaa/entries/jQuery.isFunction.xml#L10

_JavaScript function object_ is ambiguous. There are some candidates:
* ECMAScript Function Objects
> ECMAScript function objects encapsulate parameterized ECMAScript code closed over a lexical environment and support the dynamic evaluation of that code.
* Function Objects
> The Function constructor is the %Function% intrinsic object and the initial value of the Function property of the global object.
* function
> member of the Object type that may be invoked as a subroutine

([_ECMAScript 2016 Language Specification_](http://www.ecma-international.org/ecma-262/7.0/index.html))

Neither of them matches the actual implementation; `jQuery.isFunction` tests `@@toStringTag`.

**Comment by AurelioDeRosa** [comment]
@timmywil do you think it's worth clarifying considering that we have deprecated it?

**Comment by mgol** [comment]
> Neither of them matches the actual implementation; jQuery.isFunction tests @@toStringTag.

That's no longer true in the latest jQuery (and, AFAIK, that has never been a purpose).

**Comment by AurelioDeRosa** [comment]
Thanks for the answer @mgol. Closing the issue.
