### ISSUE TITLE
Clear up when .height(), .width() etc return fractional number

### ISSUE THREAD

**Issue by entis** [jquery/api.jquery.com#1038]
From [.height() documentation page](http://api.jquery.com/height/):
> The number returned by dimensions-related APIs, including .height(), may be fractional in some cases. Code should not assume it is an integer. Also, dimensions may be incorrect when the page is zoomed by the user; browsers do not expose an API to detect this condition.

I'd welcome more information on cases in which these numbers might be fractional. With current use of percentage-based layouts and subpixel rendering the difference between fraction and integer can be significant. So far I haven't been able to find out an example of .height() returning fractional number.

**Comment by dmethvin** [comment]
jQuery doesn't control when those numbers are fractional, so having jQuery document when they currently might be fractional in the currently supported browsers seems like a never-ending battle of obsolete information. Here's one example that returns fractional pixels in Chrome Windows at the moment: http://jsbin.com/mehayecolo/1/edit?html,output

**Comment by AurelioDeRosa** [comment]
There are no more actions needed here, so I'm closing this task.
