### ISSUE TITLE
Confusing behavior with jquery.ajax success

### ISSUE THREAD

**Issue by danlo** [jquery/api.jquery.com#1041]
Greetings,

https://github.com/jquery/api.jquery.com/blob/master/entries/jQuery.ajax.xml#L170

When my application responds with a status: 200 and NO content
the success function does not fire.
When my application responds with a status: 204 and NO content
the success function does fire.

I believe that adding a note that success() will not fire with a status code of 200 and no content, and that if no content is present, then to use a status: 204  This will prevent other people like me :) who were wondering why a 200 respond did not cause a fire.

Regards,

Daniel Lo

Thank you for the great work!

**Comment by dmethvin** [comment]
Hi @danlo, there is nothing wrong with returning 200 and no content, unless your server or the `$.ajax` makes some additional request, for example saying the data type is JSON. An empty request is not valid JSON. If the request said `dataType: "text"` or the server returned `Content-Type: text/plain` for example, there should be no problem at all.
