### ISSUE TITLE
XMLHttpRequest standard link outdated

### ISSUE THREAD

**Issue by hochleitner** [jquery/api.jquery.com#1043]
In the [XMLHttpRequest](https://api.jquery.com/Types/#XMLHttpRequest) section of the Types page the W3C standard for XMLHttpRequest (https://www.w3.org/TR/XMLHttpRequest/) is linked/mentioned.

W3C discontinued work on this document and gave it the status of a WG note. It's probably better to link to the WHATWG living standard at https://xhr.spec.whatwg.org/ (as mentioned in the WG note).

**Comment by mgol** [comment]
Thanks for the report. Would you like to submit a PR?

**Comment by hochleitner** [comment]
I'll do that, just need to sign the CLA first (if I'm correct), since it's me first contribution.

**Comment by mgol** [comment]
Once you submit a PR, it will ask you to submit a CLA with a direct link so don't worry about it at this moment.
