### ISSUE TITLE
$.extend(true, json1, json2) merges only one level

### ISSUE THREAD

**Issue by xtf1** [jquery/api.jquery.com#1056]
I want to interweave the nested json, only consisting of id's, with a array of json's with the corresponding id's and data.

`var hierarchy = {...},`
`roles = {...};`

but 
`$.extend(true, hierarchy.children, roles);`
interweaves only the first level.

I have created a this for better visualisation: 
[wrong_merge.js gist](https://gist.github.com/xtf1/ff684159b37728f00913656173ba3a72)

**Comment by gibson042** [comment]
This repository is for reporting bugs in documentation, not in functionality, but your use case requires very specialized behavior (using a property to tie data structures together) for which a general utility like `jQuery.extend` is inappropriate. I believe you want to implement a custom visitor that updates tree nodes from an id-to-data map: https://jsfiddle.net/txLwsggx/

**Comment by xtf1** [comment]
OK, understood. But isn't `jQuery.extend` meant for deep merging. With your code the tree is flattened what I don't want and `extend` at least merges one level deep. Do you know where I can investigate further or a common name of the topic to search for?

**Comment by mgol** [comment]
Deep merging means that if objects you merge have the same path in the object tree to specific nodes, those nodes will get merged. In your case only one of the objects is deep and the other one is very flat. The merging algorithm works as it should here, it cannot guess your intention.

What you want is way beyond a generic merge function.

**Comment by xtf1** [comment]
I wanted to append to the hierarchy the values of the flat by the corresponding ids. I don't have a idea how this would be called, maybe filling up hierarchy by dictionary or else. I see this is a dead end, but since I explained it here I thought you could help me further, by saying how this process would be called or where I have to look.

Nevertheless thank you both
