### ISSUE TITLE
The jquery3.2.1 version and then select the check box and then uncheck the point select button is invalid

### ISSUE THREAD

**Issue by ThreeGold233** [jquery/api.jquery.com#1058]
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>demo</title>
	<script type="text/javascript" src="jquery-3.2.1.js"></script>

</head>
<body>
	<form method="post" action="">
   <br/>
    <input type="checkbox" name="items" value="football"/>football
	<input type="checkbox" name="items" value="basketball"/>basketball
	<input type="checkbox" name="items" value="badminton"/>badminton
	<input type="checkbox" name="items" value="TableTennis"/>TableTennis
   <br/>
    <input type="button" id="CheckedAll" value="Select all"/>
    <input type="button" id="CheckedNo" value="unselect all"/>
    <input type="button" id="CheckedRev" value="Reverse selection"/> 
</form>

<script type="text/javascript">
  $(function(){
     $("#CheckedAll").click(function(){
	     $('[name=items]:checkbox').attr('checked', true);
	 });
     $("#CheckedNo").click(function(){
	    $('[type=checkbox]:checkbox').attr('checked', false);
	 });
     $("#CheckedRev").click(function(){
		  $('[name=items]:checkbox').each(function(){
			this.checked=!this.checked;
		  });
	 });
  })

  </script>
</body>
</html>

**Comment by mgol** [comment]
The issue template asked for a test case on jsfiddle or jsbin, reading code in an issue requires significant effort.

That said, it looks like using `attr` where `prop` makes more sense; read https://jquery.com/upgrade-guide/1.9/#attr-versus-prop- for more information.
