### ISSUE TITLE
FR: Call $.toggleClass by give JSON Object

### ISSUE THREAD

**Issue by enexusde** [jquery/api.jquery.com#1059]
Having this code:
```

    $('.foobar').toggleClass('first', index==0);
    $('.foobar').toggleClass('last', index==list.length - 1);

```
should be optimized to
```

    $('.foobar').toggleClass({
        first: index==0,
        last: index == list.length -1
    });
```

as often used in other functions like .css({}), .on({}) and one({}).

We have multiple advantages: 
 1. Its a syntax error if we have a Class containing illegal characters like a space-character. Using the current method a class having 'foo    bar' is illegal but not a syntax error. Having the feature implemented the code toggleClass({foo     bar: true}) is a syntax error.
  2. Its normalized to the other methods using JSON objects. Its intuitive. (I created this FR because i was wondering why toggleClass({}) does not work)
  3. It is one statement. See the first example above, if the second toggleClass does not work, the first should not has been executed also. In the example, if list is undefined the list.length throws an error (because undefined has no property 'length'), but the first toggleClass has been executed, we have a mixed state! Might be an edge-case, but prevent such a mixed-state will increase debuggability.

**Comment by dmethvin** [comment]
This would be a good plugin, but we're striving to keep jQuery core small and focused on essential needs.

**Comment by enexusde** [comment]
This would be a bad plug-in.
