### ISSUE TITLE
HTTP/2 and errorThrown or statusText

### ISSUE THREAD

**Issue by vkrol** [jquery/api.jquery.com#1063]
Hello!

In HTTP/2 errorThrown and statusText will be the empty strings:

>  HTTP/2 does not define a way to carry the version or reason phrase that is included in an HTTP/1.1 status line.
https://tools.ietf.org/html/rfc7540#section-8.1.2.4

I think that it should be added to this page https://api.jquery.com/jQuery.ajax/.

**Comment by mgol** [comment]
Would you like to submit a PR?
