### ISSUE TITLE
Confusing jQuery.ajax error documentation

### ISSUE THREAD

**Issue by vdhpieter** [jquery/api.jquery.com#1064]
In the documentation the function talks about a String: ErrorThrown while the descriptions says it is an optional exception object.

https://github.com/jquery/api.jquery.com/blob/5b7121ab1a7d2a1805e702eca20da180e336528c/entries/jQuery.ajax.xml#L108-L113

**Comment by dmethvin** [comment]
I don't see any mention on that page that `errorThrown` is an "optional exception object".
