### ISSUE TITLE
callbacks.fireWith has no types defined for its arguments

### ISSUE THREAD

**Issue by dratini0** [jquery/api.jquery.com#1066]
I have been processing the documentation with a python script (thank you for making it machine readable, btw!), when I noticed that the function [`callbacks.fireWith`](https://api.jquery.com/callbacks.fireWith/) has no types defined for its arguments. Since this is the only function like this, I am assuming this is a mistake. By looking at it, I am assuming they should be `Anything`, but I am not confident, since I have never used the `callbacks` object.

**Comment by gibson042** [comment]
Thanks for finding this! Per https://github.com/jquery/jquery/pull/3844 , we'd like to describe the code accurately by documenting `type="Anything"` for `context` and `type="ArrayLikeObject"` for `args` (and updating the text to match).

**Comment by dratini0** [comment]
That is almost exactly what I did in #1067, but I think you are right here. I didn't pick up on the ArrayLikeObject part, though. I will update #1067 accordingly
