### ISSUE TITLE
CI for pull requests is broken

### ISSUE THREAD

**Issue by dratini0** [jquery/api.jquery.com#1068]
With my recent PR #1067, I have noticed that the CI system is not working, all builds fail with the following message:

```
>> Missing executable: xmllint.
```

This has been the case for #1065 as well.

**Comment by dmethvin** [comment]
Yeah, we're all dreading going in to fix it. Thanks for the heads-up tho!

**Comment by AurelioDeRosa** [comment]
This has been fixed in https://github.com/jquery/api.jquery.com/pull/1080.
