### ISSUE TITLE
.attr has an undocumented signature

### ISSUE THREAD

**Issue by olleicua** [jquery/api.jquery.com#1075]
$element.attr({ class: 'red', title: 'text' }) seems to work as expected but is not documented. There is an example of it at the bottom of the page but the signature isn't documented.

Also I find it really helpful that in most of the documentation the signatures are succinctly described at the top and then the details follow. It would be nice to re-organize this. I'd be happy to take a crack at it but I'd love some input from someone more closely involved with the project as to whether such a change is likely to get merged and what is needed for that.

**Comment by dmethvin** [comment]
It's this signature: http://api.jquery.com/attr/#attr-attributes

**Comment by dmethvin** [comment]
That signature is defined at the top of the page, if you click it you'll go to the link I gave.

**Comment by olleicua** [comment]
Oh, never mind I see they are nested don't mind me

**Comment by mgol** [comment]
@dmethvin Hmm, this nesting looks wrong to me. `.attr( attributes )` doesn't match its parent's `.attr( attributeName, value )`.

**Comment by olleicua** [comment]
I agree that that is wrong, and it did in-fact confuse me.

**Comment by kswedberg** [comment]
@mgol , well, it matches in the sense that all three signatures within that parent are setters. I think the real issue is that we probably shouldn't use the first signature of each `<entry>` as the label for the parent. Not sure what would be better. Maybe `.attr( ) — Setter` or something? Would require adding an attribute to the `<entry>` tag and fiddling with the xslt a bit

**Comment by olleicua** [comment]
It looks like it is the same `css` and `prop` but oddly `data` is in the reverse order

**Comment by mgol** [comment]
@kswedberg 

> I think the real issue is that we probably shouldn't use the first signature of each `<entry>` as the label for the parent.

That sounds like the correct diagnosis.

> Maybe `.attr( ) — Setter`

Sounds good to me here; this may be a more generic problem, spanning multiple APIs, though.
