### ISSUE TITLE
Deprecate jQuery.type

### ISSUE THREAD

**Issue by jbedard** [jquery/api.jquery.com#1076]
jQuery.type is deprecated as of jQuery 3.3.

See https://github.com/jquery/jquery/issues/3605

**Comment by DanielRuf** [comment]
What is the alternative?

**Comment by DanielRuf** [comment]
So far the update breaks at least some big frameworks and testsuites.

**Comment by DanielRuf** [comment]
See https://github.com/jquery/jquery/pull/3956

**Comment by mgol** [comment]
This is now documented, the issue is obsolete.
