### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by PanderMusubi** [jquery/api.jquery.com#1096]
Please, fix broken links on the website found by W3C's link checker:

https://validator.w3.org/checklink?uri=https%3A%2F%2Fapi.jquery.com%2F&hide_type=all&recursive=on&depth=&check=Check

**Comment by marcus-hiles** [comment]
@PanderMusubi I dont see any errors here, everything seems fine, can you outline some of the stuffs needing fixing on the page?

**Comment by PanderMusubi** [comment]
At the time of reporting there were. Good that they have been fixed. Thanks for checking up on this one.
