### ISSUE TITLE
Improve documentation for jQuery html() with jQuery object signature

### ISSUE THREAD

**Issue by lennu** [jquery/api.jquery.com#1101]
Hey it's possible to pass jQuery object to html() which actually empties the container and appends the object into the container.

https://github.com/jquery/jquery/blob/ae82e85e64b0a06d585934d8f2d2859ce3e755b6/src/manipulation.js#L435

I found this through jQuery TypeScript typings where the typings have probably been made following the jQuery API. (Everytime you pass jQuery object to .html() function it's an type error)

**Comment by dmethvin** [comment]
We've declined to document this several times in the past. Yes, if you follow the code, it will do something and sometimes it's what you want. If the jQuery object is a selector to an element on the page, that page will be *moved* from its current position to a child of the element using `.html()`.  The Typescript bindings are correct.
