### ISSUE TITLE
Confusion about delegation and event handlers in .on()'s documentation

### ISSUE THREAD

**Issue by Chealer** [jquery/api.jquery.com#1103]
The Direct and delegated event handlers section in [.on()'s documentation](http://api.jquery.com/on/) contains:

> By picking an element that is guaranteed to be present at the time the delegated event handler is attached, you can use **delegated events** to avoid the need to frequently attach and remove event handlers.

As reported in ticket #1085, even though that page refers to them several times (at least on source lines 44, 45 and 46), there is no such thing as a "delegated event". "Delegated events" should read "Delegated event handlers".

**Comment by dmethvin** [comment]
We'd welcome a pull request.
