### ISSUE TITLE
[Documentation] Add a nice search experience in the website

### ISSUE THREAD

**Issue by s-pace** [jquery/api.jquery.com#1104]
👋  jQuery team,

 Following #227 that is lost in threads, I am following up and waiting fro feedback.

As web developers, we've all used jQuery in our career and we'll be forever grateful for how it changed the web development landscape for the better. But with so many versions along the years, we understand it can sometimes be hard to navigate into the documentation.

I'm working at Algolia on the a project called [DocSearch](https://community.algolia.com/docsearch/) which goal is to enhance documentation websites with exhaustive, fast and relevant search. You might have seen DocSearch live already on websites like [Bootstrap](https://getbootstrap.com/), [ESLint](https://eslint.org/) or [Babel](https://babeljs.io/).

We put together [a demo](https://docsearch-jquery.netlify.com/) of what DocSearch on the jQuery website could look like here. Feel free to try it and let us know what you think.

[![demo of DocSearch + jQuery](https://cl.ly/2D1g133n1M3F/download/Screen%20Recording%202018-08-07%20at%2009.42%20AM.gif)](https://docsearch-jquery.netlify.com/)

The way DocSearch works is by crawling your content, pushing the results into an Algolia index, and then requesting this index directly from the website front-end through JavaScript.

We'll take care of crawling your website and populating the Algolia index with the latest changes every 24h for you. You don't need to change anything to your deployment process. The only thing you need to add are the following CSS and JS snippets that will bind the dropdown to your searchbox.

```html
<!-- at the end of the HEAD -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.css" />

<!-- at the end of the BODY -->
<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/docsearch.js@2/dist/cdn/docsearch.min.js"></script>
<script type="text/javascript"> docsearch({
  apiKey: '3cfde9aca378c8aab554d5bf1b23489b',
  indexName: 'jquery',
  inputSelector: '[name="s"]',
  debug: false // Set debug to true if you want to inspect the dropdown
});
</script>
```

The `inputSelector` option should be set to a CSS selector that target your search input. Feel free to update it if this one is not specific enough.

We built DocSearch with the idea of giving back to the Open-Source community. This is why your [crawling configuration](https://github.com/algolia/docsearch-configs/blob/master/configs/jquery.json) is available on GitHub if you want to change it. We also have our own [documentation](https://community.algolia.com/docsearch/documentation/) to help you tweak the dropdown to your needs. You'll also have access to analytics on the most searched terms or those with no results. All of this is of course entirely free.

Would that be something you'd be interested in? If so, we'd be happy to work on integrating it through a PR.

**Comment by timmywil** [comment]
This looks pretty cool. I'm open to it, but would love to see how it looks on mobile and some data on how it affects page load.

**Comment by mgol** [comment]
Thanks for the proposal! I see it requires 43 KB of gzipped JS; we currently load 128 KB of JS in total. As it's not a critical part of the site I'd rather see the script loaded `async` to not delay other stuff that may wait for document ready (i.e. the `DOMContentLoaded` event). Then you'll need to somehow wait for the script to execute so your inline snippet will need to look differently. Can that be done?

**Comment by s-pace** [comment]
Thanks for your feedback.

@timmywil  our UI is mobile compliant but not really responsive, give it a try.

We are designing the v3 of our search-UI and your concern @mgol is the biggest one. We want to move away from zepto too. There is a lot of performance optimisation too. WIP

You can definitely put it as `async` 

Do you want to PR it?

**Comment by mgol** [comment]
A PR would be very much welcome!

**Comment by s-pace** [comment]
🚀  

Everything ready on our side 💪 @Shipow

Please review it @mgol @timmywil and let us know what to do 🙏
