### ISSUE TITLE
jQuery.parseJSON is missing from Deprecated 3.0 documentation page

### ISSUE THREAD

**Issue by mgol** [jquery/api.jquery.com#1116]
Reported by @TiTi at https://github.com/jquery/jquery/issues/4224.

### Description ###

[jQuery.parseJSON](https://api.jquery.com/jQuery.parseJSON/) is missing from [Category: Deprecated 3.0](https://api.jquery.com/category/deprecated/deprecated-3.0/)
(and also https://api.jquery.com/category/deprecated/)

milestone:3.0.0
#2800

### Link to test case ###

N/A

**Comment by mgol** [comment]
Thanks for the report, @TiTi. It seems we missed the category change when we added the deprecation.

**Comment by mgol** [comment]
@TiTi would you like to prepare a PR?

**Comment by TiTi** [comment]
Thank you for the opportunity, here you go. I also fix the 2 other missing entries
