### ISSUE TITLE
Build warning: Mismatching versions for Gilded WordPress

### ISSUE THREAD

**Issue by globalmatt** [jquery/api.jquery.com#1119]
Hi,

I'm attempting to set up https://github.com/jquery/jquery-wp-content for the first time, following the instructions at https://contribute.jquery.org/web-sites/ .

I've successfully installed VirtualBox and Vagrant and can access the API docs site at https://vagrant.api.jquery.com .

However, when I try to build and deploy, I get this warning:

```
~/Sites/api.jquery.com$ grunt deploy
Running "check-modules" task

Running "xmllint:all" (xmllint) task
Lint free files: 323

Running "clean-dist" task

Running "build-posts:page" (build-posts) task
Built 2 pages.

Running "build-resources:all" (build-resources) task
Built 64 resources.

Running "build-xml-entries:all" (build-xml-entries) task
Built 316 entries.

Running "build-xml-categories" task

Running "build-xml-full" task

Running "wordpress-validate" task
Warning: Mismatching versions for Gilded WordPress. Version 1.0.5 is installed as a Node.js module, but the WordPress server is running version 1.0.3. Use --force to continue.

Aborted due to warnings.
```

Using `--force` does complete the task, but no content is inserted into the WordPress site.

How can I fix this please?

Thanks,
Matt

**Comment by marcus-hiles** [comment]
Hi @globalmatt you can try downgrading your node gilded-wordpress version to 1.0.3. Try this command:

`npm install gilded-wordpress@1.0.3 --save-exact`
