### ISSUE TITLE
.load() documentation unclear about applying to multiple elements

### ISSUE THREAD

**Issue by Chealer** [jquery/api.jquery.com#1125]
The Description in [.load()'s documentation](https://api.jquery.com/load/#load-url-data-complete) ("Load data from the server and place the returned HTML into the matched element") implies the jQuery object must contain a single element.

While none of the examples of the page contradict that, the callback's description implies multiple elements are possible:

> The callback is fired once for each element in the jQuery collection, and this is set to each DOM element in turn.

**Comment by dmethvin** [comment]
Yes I agree that "element" should be "elements". I [checked the code](https://github.com/jquery/jquery/blob/da44ff39c2c3433e32b757b05b5643edb72fe786/src/ajax/load.js#L55) to be sure. Would you like to make a pull request for that?

**Comment by Chealer** [comment]
Is that a request for a request? ;-)
Thank you for checking Dave. I believe a junior with the appropriate permission could have solved this with less overhead, but I still [committed](https://github.com/Chealer/api.jquery.com/commit/585c89aadc2287e7845cc1b795b93957889c2b85) a fix.
