### ISSUE TITLE
Incomplete documentation about pseudo selector support

### ISSUE THREAD

**Issue by teo1978** [jquery/api.jquery.com#1127]
At https://api.jquery.com/first-of-type-selector/#first-of-type1

it says "version added: 1.9.0".

So, I expect it to work consistently on any browser on that version or above, AND to consistently NOT work on any version below that.

Instead, on 1.8.0 it works on most browsers but not on IE.

This MUST be properly documented.
I expect support for ANY selector to be 100% consistent across browsers unless otherwise documented. So, in this case, given we are talking about an old jQuery version, the issue is in documentation.

**Comment by mgol** [comment]
PRs to improve the documentation are welcome. The docs will never be 100% accurate, though, especially for older versions which we no longer maintain.

**Comment by AurelioDeRosa** [comment]
@teo1978 can you be more specific about which version of IE it doesn't work? :first-of-type is a selector that is supported since IE9.

**Comment by dmethvin** [comment]
If someone is using 1.8.0 still then who knows what behavior they'll find against modern browsers. We don't have the resources to go back and validate every old version of jQuery against newer browsers.

In general, if the browser happened to support a selector then it will work in that browser, even if it wasn't supported by jQuery at the time.

**Comment by teo1978** [comment]
> In general, if the browser happened to support a selector then it will work in that browser, even if it wasn't supported by jQuery at the time.

That seems to be the piece of documentation that I was missing. The fact that there are selectors supported natively by the browsers, and only when they are not jQuery implements its own.

Maybe that *is* actually documented somewhere.
