### ISSUE TITLE
Undocumented difference in behavior of 1.9.1 vs every other version before and after

### ISSUE THREAD

**Issue by teo1978** [jquery/api.jquery.com#1128]
Steps to reproduce:

Try these:

1. http://matteosistisette.com/test/stupidjquery/4/?jqver=1.8.0
2. http://matteosistisette.com/test/stupidjquery/4/?jqver=1.9.0
3. http://matteosistisette.com/test/stupidjquery/4/?jqver=1.9.1
4. http://matteosistisette.com/test/stupidjquery/4/?jqver=3.0.0

It's the same code running with different  versions of jQuery as you can guess from the query string.

**Expected Result:**
They should all behave like the first one, where the text "here's some text"  is replaced by the text "Replacement Replacement" (with the first word in red)

**Observed Result**:
All except the second one (jQuery 1.9.0) behave as expected, but in the second one (1.9.0) the text node doesn't get replaced.

This example takes a TEXT node and replaces it with some html code. Note that, by the console output, you can tell that the text node is found in all version; however on 1.9.0 the replaceWith() has no effect.

There are documented changes in how replaceWith() behaves, documented both [here](https://jquery.com/upgrade-guide/1.9/#after-before-and-replacewith-with-disconnected-nodes) and [here](https://api.jquery.com/replaceWith/#replaceWith-newContent) :
> Prior to 1.9, .after(), .before(), and .replaceWith() would attempt to add or change nodes in the current jQuery set if the first node in the set was not connected to a document, and in those cases return a new jQuery set rather than the original set. [...] As of 1.9, these methods always return the original unmodified set and attempting to use .after(), .before(), or .replaceWith() on a node without a parent has no effect--that is, neither the set or the nodes it contains are changed.

However, this does NOT explain the difference in behavior observed in the above examples.

Obviously this was some bug introduced in 1.9.0 (possibly related to the abovementioned documented change, but that's just my guess) that was then fixed in the later versions, but this should be documented.

I do expect all changes in behavior between versions to be documented, whether they are intentional or due to bugs.

**Comment by AurelioDeRosa** [comment]
I'm a bit reluctant on documenting this since it seems a bug to me. If we start documenting all the bugs that were ever introduced, the documentation would become less useful in my opinion. I'm keen to hear other opinions here.

**Comment by dmethvin** [comment]
I agree here, if we documented anything it would be against the tip of the 1.x branch. Documenting the bugs of every version would make the docs very hard to read.

**Comment by teo1978** [comment]
> Documenting the bugs of every version would make the docs very hard to read.

Not necessarily. There are a number of easy ways to do it without making it difficult to read. For example adding a specific section on each page (e.g. at the end) with a comprehensive history of changes related to the feature the page is about. And if you want, separate those due to known bugs in a subsection, but I don't see a need for that. Or add a section with links to bugs related to the feature.

To the user, knowing that there was a bug that affected the behavior of a feature that appeared on version X and was fixed on version Y is exactly as vital as it is to know that a given behavior was changed intentionally.

**Comment by dmethvin** [comment]
There aren't a lot of reasons for users to be stuck on, say, 1.8.1. The latest 1.x is 1.12.4 and the latest 2.x is 2.2.4. I suppose someone could try and make the case that it's easier for *them* to stay on 1.8.1 and try to make everyone else including the jQuery team document whether and how things work on 1.8.1 but that's not efficient for anyone but them.
