### ISSUE TITLE
(append|prepend|before|after) now accept an array of jQuery objects.

### ISSUE THREAD

**Issue by mikesherov** [jquery/api.jquery.com#113]
please see this commit for examples: https://github.com/jquery/jquery/commit/ea9ec9527647f0cea396ca536e6f34b4a4491d11

**Comment by arthurvr** [comment]
This was fixed in https://github.com/jquery/api.jquery.com/commit/eb43c5fcfd0b7421167d1d35aa4e105def5e41b1, isn't it?
