### ISSUE TITLE
jQuery( null/undefined ) behavior?

### ISSUE THREAD

**Issue by biziclop** [jquery/api.jquery.com#1136]
Hi, I read the documentation for `jQuery()` at https://api.jquery.com/jQuery/ but I haven't found the official behavior for passing a single `null` or `undefined` value (or maybe other falsy values too, like `false`, `0`, `''`) to `jQuery()`.

Currently `null` and `undefined` (and other falsies) return an empty set, which is the behavior I would prefer, but I can't know from the docs if I can depend on it.

It's simpler to write `$( elementOrNull )` than `elementOrNull ? $( elementOrNull ) : $()` or `$( elementOrNull || [])`.

Thanks!

**Comment by dmethvin** [comment]
Thanks for asking! We define `jQuery()` with no arguments to return an empty set as of version 1.4, but you're right that there doesn't seem to be any explicit documentation about `jQuery(undefined)` or `jQuery(null)`. We do have [unit tests](https://github.com/jquery/jquery/blob/438b1a3e8a52d3e4efd8aba45498477038849c97/test/unit/core.js#L63-L66) to guarantee they return an empty set though so you can count on it working.

Probably the easiest way to document this is to [replace this sentence](https://github.com/jquery/api.jquery.com/blob/25b47f5b54cf574e53f793eb0035dbf6107a3797/entries/jQuery.xml#L80) and say, "Calling the jQuery() method with no arguments returns an empty jQuery set (with a `.length` property of `0`). Similarly, If an argument of `null`, `undefined`, an empty array (`[]`), or an empty string (`""`) is passed, the set contains no elements." At this point I don't think the comment about "as of jQuery 1.4" is useful considering that jQuery 1.3.2 is coming up on its tenth birthday.

**Comment by biziclop** [comment]
Thanks, I made a pull request with your sentence, I hope it's usable.
