### ISSUE TITLE
Unable get HTML fragment on any selector

### ISSUE THREAD

**Issue by WHK102** [jquery/api.jquery.com#1138]
In Google Chrome (last version) and jQuery 3.4.1, using custom HTML tags, by example:

`<template data-id="row"><tr><td data-text="{foo}"></td></tr></template>`

I iterate all tags with `data-text` property for translate the data-text:

```
    $('[data-text]').each(function(){
        $(this).text(strings[$(this).attr('data-text')]);
    });
```

On all html tags works fine, but on inner custom tags is not work, but i can access to it using:

`$('template[data-id="row"]').contents().find('[data-text]')`

jQuery omit the custom tags (html fragments)?

**Comment by mgol** [comment]
`<template>` contents are not regular DOM elements, they are inert and meant for future use. Therefore, browser APIs don't return inner `<template>` elements when using `querySelectorAll` which also affects jQuery. Using `.contents()` on a template element means you explicitly want to look inside of such an element and we now support doing that.

I don't see any bug here so I'll close the issue.

**Comment by mgol** [comment]
Also, this is a bug tracker for the API documentation, the jQuery bug tracker is at https://github.com/jquery/jquery/issues.

**Comment by WHK102** [comment]
But `querySelectorAll` works fine with custom tags, but using jquery is not work:

- https://jsfiddle.net/4t4tcr3w/
- https://stackoverflow.com/questions/38159932/use-custom-tag-using-javascript-only

Tested on Firefox 68.0 and Google Chrome 75.0. The non regular tags are parts of DOM without default style and hide by default, by example:

`<x style="display: block; color:black;background-color:red;">Test</x>`

And works fine using onclick and special javascript callable events.

Its not a Javascript problem.
