### ISSUE TITLE
$.html works improperly

### ISSUE THREAD

**Issue by htta17** [jquery/api.jquery.com#1163]
jQuery version: 3.4.1

Hi jQuery docs team!

I have tried to use JQuery 3.5.1 and ran 
`$("<div><style/>Elon</div>").html()` 
and received 
`"<style>Elon</div></style>"`

I have tested on Chrome, Firefox, Edge and saw the same result.

**Comment by mgol** [comment]
Thanks for the report. The change is intended. Please see https://github.com/jquery/jquery/issues/4710#issuecomment-625440530
