### ISSUE TITLE
Description for jQuery post () method does not seems to be correct. 

### ISSUE THREAD

**Issue by nikolaij** [jquery/api.jquery.com#1165]
jQuery.post()
Load data from the server using a HTTP POST request. at https://api.jquery.com/category/ajax/shorthand-methods/
this should be "send data to server" Of cause Post return back a full data that was sent to the server with new Id created. But main purpose is to send data to the storage as Data base for example not to load data from the server as description says

**Comment by mgol** [comment]
Thanks for the report. Would you like to submit a PR? The text is at https://github.com/jquery/api.jquery.com/blob/5f41b2d722c0120b052dcaf166c682daecdfaa80/entries/jQuery.post.xml#L30

**Comment by nikolaij** [comment]
Hi mgol not sure what you mean "... submit a PR"

**Comment by mgol** [comment]
PR means Pull Request. :) In other words, a fix for the issue you reported for which you'll be credited. Some details are available at https://contribute.jquery.org/commits-and-pull-requests/.

**Comment by nikolaij** [comment]
Thanks Michal

I did pull and committed change to the file. But did not put the description
I will try to do it now

Best regards
Nikolai

Sent from Mail for Windows 10

**Comment by mgol** [comment]
Fixed by #1166, thanks!

**Comment by nikolaij** [comment]
Thank You

Sent from Mail for Windows 10
