### ISSUE TITLE
String.prototype.trim() isn't 100% compatible with jQuery.trim()

### ISSUE THREAD

**Issue by ssg** [jquery/api.jquery.com#1174]
`jQuery.trim(null)` returns an empty string while `null.trim()` throws the error "Uncaught TypeError: Cannot read property 'trim' of null" 

The documentation page implies that it is a direct replacement. One should be aware of the consequences. It might help to note the potential issues when removing calls to $.trim() for all the users migrating to jQuery 3.5+.

`String.prototype.trim.call(null)` also throws "Uncaught TypeError: String.prototype.trim called on null or undefined".

**Comment by dmethvin** [comment]
The docs mention that the argument should be a string. With argument values that aren't strings, the two approaches might definitely diverge but those are undocumented usages. For example, `jQuery.trim(5)` returns `"5"`. The goal of the advice there is to help people find reasonable alternatives but we can't rewrite their code to handle every case, especially ones that use the API in ways that contradict the documentation. What alternative would you suggest? 
.

**Comment by ssg** [comment]
I suggest adding a note about possible incompatibility issues along with suggestion for the replacement in the documentation.

**Comment by dmethvin** [comment]
If you have specific suggestions please make a pull request.

**Comment by ssg** [comment]
@dmethvin thanks, done. #1175
