### ISSUE TITLE
Cloudflare email protection false positive

### ISSUE THREAD

**Issue by Uristqwerty** [jquery/api.jquery.com#1177]
Upon opening https://api.jquery.com/category/selectors/, I immediately saw

"To use any of the meta-characters ( such as  `!"#$%&'()*+,./:;<=>[[email protected]](https://api.jquery.com/cdn-cgi/l/email-protection)[\]^`{|}~` ) as a literal part of a "

Presumably cloudflare hit a false positive there, so because I hadn't whitelisted the page for JavaScript, the documentation was ever-so-slightly mangled.

**Comment by mgol** [comment]
I don't see this... Is this behavior reproducible?

**Comment by Krinkle** [comment]
It's quite likely that this protection was enabled at some point in the past as part of a bulk preset in the Cloudflare configuration. I've removed various such filters over the past months, putting things on the Nginx server configuration where possible to reduce vendor lock-in, or to remove them entirely.

This particular feature from Cloudflare is known as "Email Address Obfuscation" which is not currently enabled for `*.jquery.com`.
