### ISSUE TITLE
developer.mozilla.org Node.nodeType link changed

### ISSUE THREAD

**Issue by biziclop** [jquery/api.jquery.com#1185]
At the documentation page  
https://api.jquery.com/contents/  
https://github.com/jquery/api.jquery.com/blob/e5f5d6ca8f216a037bb9896fa01d8eb766ebf6ec/entries/contents.xml  
`Node.nodeType` links to  
https://developer.mozilla.org/docs/en/DOM/Node.nodeType  
but meanwhile the proper link changed to:  
https://developer.mozilla.org/en-US/docs/Web/API/Node/nodeType  

Other MDN links appear to be good:  
https://github.com/jquery/api.jquery.com/search?q=developer.mozilla.org

**Comment by mgol** [comment]
Thanks for the report; would you like to submit a PR?

**Comment by mgol** [comment]
This has been fixed independently.
