### ISSUE TITLE
Error in prop() documentation, regarding statement about checkbox state and attr()

### ISSUE THREAD

**Issue by jayschmidgall** [jquery/api.jquery.com#1194]
On this page:
http://api.jquery.com/prop/

this line of text seems wrong:

"$(elem).attr("checked") (1.6.1+) "checked" (String) Will change with checkbox state"

shouldn't this read, "Initial state of the checkbox; does not change" instead?

The Example just below it seems to support my opinion.

#288 initially recorded this problem, but the resolution, #1180, seems to have corrected the attr documentation but not the prop documentation, as it is still in the prop documentation.

**Comment by mgol** [comment]
Thanks for the report. Would you like to submit a PR with a fix?
