### ISSUE TITLE
addClass documentation should mention duplicates ignored

### ISSUE THREAD

**Issue by Danny8bit** [jquery/api.jquery.com#1196]
The [documentation](https://api.jquery.com/addClass/) should mention that it's not necessary to check whether the class attribute already has the class name(s), as a request to add an existing class name is ignored.

If jQuery has not always done this, the version when this was first done should be mentioned, i.e. in early versions could a duplicate class name be added?

As a matter of interest, preventing the addition of duplicate class names is apparently not something browsers do (tested Chrome and Firefox), where changing the className property (or attribute), where had this been the case, I wouldn't have known whether jQuery or the browser was doing this (without stepping in to the jQuery source code).

**Comment by timmywil** [comment]
We won't be adding this at this time.

**Comment by Danny8bit** [comment]
I just thought it was worth mentioning that you ignore attempts to add a class that is already added to the element, given that you went to the trouble of coding this, and I imagine I can't be the first person who wondered whether you implemented this, where if you didn't block duplicates, this can and has caused issues in the past.
