### ISSUE TITLE
typo in demo answers

### ISSUE THREAD

**Issue by n-khosh** [jquery/api.jquery.com#1201]
In [Attribute Equals Selector [name=”value”]](https://api.jquery.com/attribute-not-equal-selector/) found a typo , one of demo answers should be 'name?'

![image](https://user-images.githubusercontent.com/23635655/162517346-73fe31c6-79e9-4397-9de8-5ca9dcd912a1.png)

**Comment by mgol** [comment]
You linked to a different page, the correct one is https://api.jquery.com/attribute-equals-selector/. But, anyway, the example looks correct to me. Please read it more carefully.
