### ISSUE TITLE
Typo in .removeAttr() example

### ISSUE THREAD

**Issue by cjbonn** [jquery/api.jquery.com#1226]
Source: [https://api.jquery.com/removeattr/](https://api.jquery.com/removeattr/)

The example includes a rogue ")" in the button selector, which I believe causes the example to malfunction.

**Comment by mgol** [comment]
Thanks! I’m on vacation right now but feel free to submit a PR with a fix (see the `entries` folder).

**Comment by cjbonn** [comment]
Not on my PC at the moment, do you need another PR for this?

**Comment by cjbonn** [comment]
@mgol (tagging, not sure if you'll see closed issue comments otherwise)

**Comment by mgol** [comment]
Yes, PRs are still welcome, I can’t fix it myself for at least the next few days. If you plan to submit a PR, please comment on that other issue to avoid possibly duplicating work. Thanks!
