### ISSUE TITLE
Document changes in boolean attributes treatment

### ISSUE THREAD

**Issue by mgol** [jquery/api.jquery.com#1243]
See https://github.com/jquery/jquery/pull/5452

**Comment by gibson042** [comment]
The table in [`.attr( attributeName )`](https://api.jquery.com/attr/#attr1) will need a new row for 4.0+, and [`.attr( attributeName, value )`](https://api.jquery.com/attr/#attr2) will need updates to document the acceptability of a `false` value and its removal behavior which is similar to `null` behavior except with "aria-" attributes.

Proposed text for the latter:
> Note: because [ARIA](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA) attributes frequently associate behavior with "false" values that differs from attribute absence, passing `false` as the value for an attribute whose name starts with "aria-…" will stringify that value to "false" rather than remove the attribute. To guarantee removal of an attribute, provide `null` as the value or use the `.removeAttr()` method.

**Comment by mgol** [comment]
PR: #1254
