### ISSUE TITLE
Documentation error for text()

### ISSUE THREAD

**Issue by jackdeguest** [jquery/api.jquery.com#1244]
### Description ###
The jQuery documentation for `text()` at [https://api.jquery.com/text/](https://api.jquery.com/text/) states:

    The .text() method cannot be used on input elements. For input field text, use the .val() method.

But this is factually incorrect. jQuery allows a text value to be passed to an input, or any other empty tags such as `<img />` for that matter. The provided content can instead be visible after the element on the console, as a child, although it will not show in the DOM.

For example, consider the following HTML chunk:

    <p><input /></p>

The following code

    $('input').text( "Hello" );

will render:

    <p><input />Hello</p>

Thus, the statement that "**.text() method cannot be used on input elements**" is factually incorrect, and maybe should be replaced with ".text() method **should** not be used on input elements"

Also, it should be added that the text thus provided will be added as a hidden child of the element.

**Comment by dmethvin** [comment]
See https://github.com/jquery/api.jquery.com/issues/1244

**Comment by dmethvin** [comment]
So my point above was that it is not desirable to document the behavior of `.text()` on an `<input>` because the API provides better and more logical ways to do that. If the mention of the `.text()` method is confusing we should just remove it, or change "cannot" to "should not", or some other wording to indicate that it's not supported and may not behave the same way in some future version.

**Comment by jackdeguest** [comment]
> If the mention of the `.text()` method is confusing we should just remove it, or change "cannot" to "should not", or some other wording to indicate that it's not supported and may not behave the same way in some future version.

It would probably be best indeed, because this is not just an issue with `input`, but the same undesirable effect also occurs with any empty tags such as `img`
