### ISSUE TITLE
Printable documentation 

### ISSUE THREAD

**Issue by anonimo82** [jquery/api.jquery.com#1249]
Please, can you provide a single page, printer friendly documentation, or at least a downloadable pdf?

Thanks in advance for any help, regards, have a nice day. 

Edit: Nevermind, it's enough if you tell me how to generate HTML documentation from this repository.

**Comment by anonimo82** [comment]
If you tell me how to generate HTML documentation, I can attempt to:
`for i in *.html; do pandoc -f html -t pdf -o $i.pdf $i; done`
then join the PDFs with another package called pdfarranger.

All with Linux, IDK how would I've been done with Windows.... Of course a solution would exist, but IDK it.
If is anyone interested, I can send the final PDF.

Thanks everyone.

**Comment by mgol** [comment]
Thanks for the report.

I don't think we'd like to maintain a separate PDF distribution, but our print styles could definitely use some work. Here's an example of the first page of https://api.jquery.com/addClass/ printed in Chrome 128.0.6613.85 on macOS:
<img width="605" alt="Screenshot 2024-08-28 at 00 04 35" src="https://github.com/user-attachments/assets/f6c7192a-bb47-456b-93fc-7505d657c590">
It's not trivial to set up jQuery content sites locally at the moment, but if you have any suggestions for print CSS that would make it look better (which you can test in browser DevTools), adding them to [`base.css` of the main `jquery` theme](https://github.com/jquery/jquery-wp-content/blob/main/themes/jquery/css/base.css) would apply here.

PRs welcome!

**Comment by anonimo82** [comment]
Uhm, IDK really. 
I'd face it when I'll have HTML files for documentation, given I'm provided instructions how ro build them.

**Comment by mgol** [comment]
If you want to run the sites locally, https://github.com/jquery/jquery-wp-docker has a description of the setup. That said, it involves running Docker, generating certificates, creating the database, etc. For this specific task, it's much easier to just [save the `base.css` file for overrides using built-in Chrome DevTools feature](https://developer.chrome.com/docs/devtools/overrides) and modify this file - you can even open it in your favorite editor as overrides are just files on the disk.

**Comment by mgol** [comment]
You can also emulate print media queries via DevTools Rendering feature: https://stackoverflow.com/questions/9540990/using-chromes-element-inspector-in-print-preview-mode

That should let you work on fixing the issue.

As for how to later generate HTML files to convert to PDFs - you can get a list of pages from the sitemap at https://api.jquery.com/wp-sitemap.xml, and download them via https://github.com/Y2Z/monolith. I tried it and it seemed to work just fine for [the `addClass` page](https://api.jquery.com/addClass/).

**Comment by anonimo82** [comment]
No, I'm looking for locally having .html files to process as I see fit

**Comment by mgol** [comment]
`monolith` generates HTML files. What else do you need?

**Comment by anonimo82** [comment]
Something similar to
`npm run doc`
For the YUIDoc NPM Package, which generates local .html files from documentation.
I had a look at monolith and as a crawler as it is, I'm afraid is stupid like HTTrack, so I guess it would not correctly parse the html input.
Correct me if I'm wrong, but meanwhile, please, anything like YUIDoc?

**Comment by anonimo82** [comment]
Look, I made it in a weird way:
First, I opened the API Documentation with any browser, then I downloaded the page as-is with "save page as" browser feature.
I then opened the HTML result with BlueGriffon, and I stripped down the left sidebar and the top menu etc.
Finally, when all I've been left with was only links, I did a `wget -mpk -F -i {name of the saved html file}`, it downloaded a webpage for each link.
Sadly, each webpage still had left and top contents, so it's my choice to strip them back or keep them, but anyhow, I can now use pandoc to convert the documentation to PDF.
Phew...

Thanks for your input by the way, it inspired me to find this solution.

**Comment by anonimo82** [comment]
Hello again. Here what I did so far:

1) `wget -mpk -F -i jQuery[UI/Mobile].html -l 1 -N --show-progress -nc `
2) open one html file and strip off unneeded content
3) create a patch file from winmerge using the original html file and the stripped off one, save as result.txt (I used `wine` here)
4) patch all html files with that patch, creating patch files on the fly with a script (code following - don't forget to adjust paths. You'll have errors, don't worry, it'll work ok)
```
#!/usr/bin/bash

cd /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/
for i in *; do {
echo "diff -U3 /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/$i/index.html /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/$i/$i.html $'\n'
--- /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/$i/index.html	`date +"%a %b %d %H:%M:%S %Y"` $'\n'
+++ /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/$i/$i.html	`date +"%a %b %d %H:%M:%S %Y"`" > /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/$i/tmpDiff.patch
cat /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/result.txt >> /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/$i/tmpDiff.patch
cd /home/io/Scaricati/jquery/jquerymobile/api.jquerymobile.com/$i/
patch index.html tmpDiff.patch
cd ..
} done
```
5) rename all html files with a script (code following)
```
#!/usr/bin/bash

cd /home/io/Scaricati/jquery/jquery/api.jquery.com/
for i in *; do {
cd /home/io/Scaricati/jquery/jquery/api.jquery.com/$i/
mv index.html $i.html
cd ..
} done
```
6) copy all html files with the following command: `cp -R -f ./*/*.html ../htmlfiles/`
7) adjust the wp-contents folder contents (file names) by removing garbage characters (navigate all the subfolder tree) - You'll need this if you use wget
8) convert all html files tot pandoc with the following command (comiing soon)
9) convert then to pdf still with pandoc with the following command (comiing soon)

Thanks a lot
