### ISSUE TITLE
Method return values should be included with parameter list

### ISSUE THREAD

**Issue by mpetrovich** [jquery/api.jquery.com#134]
The return values of API methods are not listed along with parameters. Instead, they're (sometimes) in the paragraph description of the method, which makes it difficult to determine how certain methods should be used (chaining vs not).

Example:
It's not immediately obvious that $.replaceWith() returns the replaced node unless one reads through the entire method description.

**Comment by AurelioDeRosa** [comment]
Is this still a valid issue?

**Comment by dmethvin** [comment]
I have said elsewhere that I thought there should be two return values in Types, one to represent the case where the original jQuery set is returned and another for the case where the set is stacked and a new set is returned.  That way you'd know whether it should use `.end()` somewhere down the road.

For the case above where you want to know what is actually in the new set, it's a tall order to put all that info into `Returns`.  The text of each entry basically spends all its time trying to describe the new set! I think the short change @kswedberg made there is good and might be a good pattern for solving the problem if it comes up elsewhere.

**Comment by dmethvin** [comment]
I'm going to close this issue. If someone identifies specific places where we need to improve an API it can be done with a new ticket.

**Comment by DanKaplanSES** [comment]
@dmethvin I would literally like to have this everywhere like @mpetrovich 's image. Should I create a separate ticket for each page of documentation?

**Comment by dmethvin** [comment]
Are you volunteering to create several dozen tickets that request a change? Or to investigate and write a short sentence about exactly what is returned with each API call? I don't think we need the former, but could use the latter.
