### ISSUE TITLE
Add an entry for $.cssNumber to the API docs

### ISSUE THREAD

**Issue by mikesherov** [jquery/api.jquery.com#164]
I think it would be worthwhile adding an entry for $.cssNumber to the API docs, alongside the existing entry for $.cssHooks.

At present, the only mention of it is right at the bottom of the entry for $.cssHooks, and so it's very easy to miss.

The main reason I think it might be a useful addition is for anyone wondering why setting the line-height style without a value does not give the same results as setting the font-size style without a value, e.g.:

```javascript
        var size = 10;
        el.css({ fontSize:size, lineHeight:size });
```

Personally, I'd add it to both the "CSS" and "Mainpulation -> Style Properties" categories, as those would be the places I'd be looking if I had the aforementioned issue.

**Comment by arthurvr** [comment]
+1, somebody wanting to take this?

**Comment by arthurvr** [comment]
On it. @dmethvin or anyone else: added in 1.4.3, is that right?

**Comment by arthurvr** [comment]
This ticket has been open for years too long so here we go: https://github.com/jquery/api.jquery.com/pull/693.
