### ISSUE TITLE
Don't encourage non-Array usage in .trigger(event, data)

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#178]
http://bugs.jquery.com/ticket/10320

Current:

The event object is always passed as the first parameter to an event handler, but if additional parameters are specified during a .trigger() call, these parameters will be passed along to the handler as well. To pass more than one parameter, use an array as shown here. As of jQuery 1.6.2, a single parameter can be passed without using an array.

Suggested

The event object is always passed as the first parameter to an event handler. An array of arguments can also be passed to the .trigger() call, and these parameters will be passed along to the handler as well following the event object. A single string or numeric argument can be passed without being wrapped in an array.

**Comment by mitar** [comment]
I think type of the argument should then also be changed from `Type: Array or PlainObject` to `Type: Array or String or Number`.
