### ISSUE TITLE
Attempting to get dimensions of a hidden div that has a percentage width/height set will result in incorrect results

### ISSUE THREAD

**Issue by mikesherov** [jquery/api.jquery.com#197]
Please see: http://bugs.jquery.com/ticket/9945 
http://bugs.jquery.com/ticket/9945#comment:18

My suggestion is to mention that querying the dimensions of hidden elements (either directly, or children of hidden elements) is discouraged, and may produce incorrect results under certain circumstances like getting the pixel width of an element that was set with a percentage.

**Comment by dmethvin** [comment]
*"Doctor, what's wrong with my API?"*
"It's inaccurate!"
*"I want a second opinion!"*
"OK, it's slow too!"

https://github.com/jquery/jquery/issues/2108

This is related to the problem of forcing layout.

**Comment by arthurvr** [comment]
Dave, you got assigned to this, is this something you'd like to take?
