### ISSUE TITLE
Link needed for jQuery Reference Guide book

### ISSUE THREAD

**Issue by rdworth** [jquery/api.jquery.com#212]
Part of our agreement with Packt is that we have some kind of acknowledgment for their signification contribution to api.jquery.com in the form of a link to the jQuery Reference Guide. On the old site, that looked like

![Screen Shot 2013-01-09 at 1 55 56 PM](https://f.cloud.github.com/assets/107824/54509/a6c88e96-5a96-11e2-8893-5e25ede41d0e.png)

We need some similar kind of treatment on the new site.

**Comment by kswedberg** [comment]
This is no longer needed.
