### ISSUE TITLE
Restore API Typeahead Search (from original api.jquery.com)

### ISSUE THREAD

**Issue by rpncreator** [jquery/api.jquery.com#227]
The old API site used to have typeahead search (filtering as user typed in search box).

This would bring feature parity back from the previous version.

**Comment by AurelioDeRosa** [comment]
I think this issue can be closed as wontfix. Currently, none of the current API websites include such features. Any thoughts?

**Comment by mgol** [comment]
https://github.com/jquery/api.jquery.com/issues/1104 has been solved so I think we can close this one as well.
