### ISSUE TITLE
jQuery() (no arguments) description is ambiguous

### ISSUE THREAD

**Issue by ajpiano** [jquery/api.jquery.com#232]
## http://api.jquery.com/jQuery/

jQuery()
## This method does not accept any arguments.

This is confusing, because the method _does_ accept arguments, as in the 5 signatures above it. The docs go on later to explain that jQuery() is used to supply an empty jQuery collection, but the descriptoin is still unintuitive. I do believe the "This method does not accept any arguments" is happening automatically, as a result of there...being no arguments in the xml

**Comment by arthurvr** [comment]
> so I think we should special-case it for this jQuery() version to say "Creates an empty jQuery object" (if we can)

So then we need to figure it out. Can we?

**Comment by dmethvin** [comment]
I don't see the text "This method does not accept any arguments" in the current page, does still need to be fixed?

**Comment by arthurvr** [comment]
Now there only is "This signature does not accept any arguments.", which is correct. Let's close this issue.
