### ISSUE TITLE
Ajax jqXHR.statusCode( map ) missing documentation

### ISSUE THREAD

**Issue by dcherman** [jquery/api.jquery.com#245]
statusCode is missing any kind of documentation - not the option mind you, but the method on the returned jqXHR.  https://github.com/jquery/jquery/blob/master/src/ajax.js#L396-L410

I pinged @jaubourg and he confirmed it should be a part of the public API

**Comment by stelovsky** [comment]
Why closed? The issue still persists.

**Comment by kswedberg** [comment]
It's mentioned in [jQuery.ajax documentation](https://api.jquery.com/jquery.ajax/) as one of the properties and methods that the jqXHR object exposes "For backward compatibility with XMLHttpRequest, a jqXHR object will expose the following properties and methods…"

**Comment by gibson042** [comment]
This should be improved by gh-1020 as well.
