### ISSUE TITLE
jQuery.when - multiple Deferred objects passed

### ISSUE THREAD

**Issue by fastfasterfastest** [jquery/api.jquery.com#262]
http://api.jquery.com/jQuery.when/ states:  *If the master Deferred is resolved, it is passed the resolved values of all the Deferreds that were passed to jQuery.when. For example, when the Deferreds are jQuery.ajax() requests, the arguments will be the jqXHR objects for the requests, in the order they were given in the argument list.*

However, I think the last sentence is incorrect. I believe the resolved values of a jQuery.ajax() request is NOT a jqXHR object as that sentence states, but rather three values - data, textStatus and the jqXHR object.

Thus, the last sentence should be changed to something along the lines:  *For example, when the Deferreds are jQuery.ajax() requests, the arguments will be an array for each of the requests (each array containing data, textStatus and the jqXHR object of the request), in the order they were given in the argument list.*

**Comment by AurelioDeRosa** [comment]
I think this issue has been addressed by PR #545 so it can be closed.
