### ISSUE TITLE
Possible bug in prop() documentation, regarding statement about checkbox state and attr()

### ISSUE THREAD

**Issue by jwatkin** [jquery/api.jquery.com#288]
On this page:
http://api.jquery.com/prop/

this line of text seems wrong:

"$(elem).attr("checked") (1.6.1+)   "checked" (String) Will change with checkbox state"

shouldn't this read, "Initial state of the checkbox; does not change" instead?

The Example just below it seems to support my opinion.

Jim

**Comment by Krinkle** [comment]
Seems to be still there. <http://api.jquery.com/attr/> states:

> $( elem ).attr( "checked" ) (1.6)	"checked" (String) Initial state of the checkbox; does not change
> $( elem ).attr( "checked" ) (1.6.1+)	"checked" (String) Will change with checkbox state

Thus suggesting that in the latest stable version, the returned attr value does change with the live state. Aside from whether that's desirable, the current demo does not match this statement. The demo (using jQuery 1.10.2 as of writing) shows a constant value of "checked" regardless of the checkbox's state.

I can reproduce the same behaviour in jQuery 2.1.3 (value unaffected by the live state).
