### ISSUE TITLE
Wrong behavior described for multiple elements in append-ish methods

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#318]
> If there is more than one target element, however, cloned copies of the inserted element will be created for each target after the first.

should be

> If there is more than one target element, however, cloned copies of the inserted element will be created for each target except the last.

Affects `.append()`, `.prepend()`, `.appendTo()` etc.

**Comment by arthurvr** [comment]
It looks like for `append()` and `prepend()` this is already fixed. I'm opening a PR for the other entries.
