### ISSUE TITLE
jQuery.Event doc does not mention .isTrigger

### ISSUE THREAD

**Issue by 2is10** [jquery/api.jquery.com#319]
http://api.jquery.com/category/events/event-object/

It's often helpful to distinguish whether an event handler was triggered programmatically via `.trigger` or `.triggerHandler`. The `.isTrigger` property on `jQuery.Event` objects seems to be provided for exactly that purpose. It would be more discoverable if the API docs mentioned it.

Currently, the [top answer to this question on stackoverflow](http://stackoverflow.com/questions/6692031/check-if-event-is-triggered-by-a-human) is a bit more verbose: `event.originalEvent === undefined`

**Comment by MacroMan** [comment]
With this property still available, is it now time to actually document this feature?

**Comment by AurelioDeRosa** [comment]
@dmethvin I'm reopening this issue to get your input here. If this is something not meant for public use, feel free to close it again.

**Comment by dmethvin** [comment]
We've been talking about trying to use the native event object for jQuery 4, in which case we wouldn't be pushing foreign properties into it. I still think that in most cases there are better ways to detect this that don't require jQuery internals.

**Comment by MacroMan** [comment]
Would it be wise to document the recommended/better way to achieve this? I've had to use this property several times now.

**Comment by dmethvin** [comment]
Ideally you'd ask that question on StackOverflow, it's not a question that would be answered by API docs since it's a "how do I..." instead of one asking how a particular API works.

As for how, it depends on what you're doing. A simple case might be
```js
$("p").on("click fake_click", function( e ) { 
   if ( e.type === "fake_click" ) ...
}).trigger("fake_click");
```

**Comment by MacroMan** [comment]
I agree. Feel free to close the ticket again.
