### ISSUE TITLE
Document $.when() returns a resolved promise if given no arguments

### ISSUE THREAD

**Issue by Krinkle** [jquery/api.jquery.com#342]
When using $.when with an array (through `.apply`):

```js
var arrayOfDeferreds = [];
/* ...*/

$.when.apply( $, arrayOfDeferreds )
    .done( function () { } );
```

It works as expected even if the array remains empty (e.g. when aggregating return values of other parts of the application and collect promises) based on the way the code is currently implemented in jQuery core.

Could this behaviour be documented / officially supported (that giving it no arguments returns a resolved promise).

**Comment by arthurvr** [comment]
:+1: I can PR this.

> documented / officially supported

@timmywil @dmethvin Are we okay with this? I'm a +1 for sure.

**Comment by dmethvin** [comment]
Yes, we get this question every few months.

**Comment by timmywil** [comment]
:+1:
