### ISSUE TITLE
.data() docs still mention .data("events")

### ISSUE THREAD

**Issue by jzaefferer** [jquery/api.jquery.com#346]
Found here: http://api.jquery.com/data/

> jQuery itself uses the .data() method to save information under the names 'events' and 'handle', and also reserves any data name starting with an underscore ('_') for internal use.

That was removed in 1.8: http://blog.jquery.com/2012/08/09/jquery-1-8-released/

Since it's really useful for debugging, the replacement for that (`$._data(element, "events")`) should be documented somewhere, along with the note that the data structure is not supported and can change anytime.

**Comment by arthurvr** [comment]
PR: #623
