### ISSUE TITLE
Callback (or null placeholder) is required for .get()/.post() if dataType is provided

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#351]
See http://bugs.jquery.com/ticket/12233 and http://bugs.jquery.com/ticket/14211

**Comment by arthurvr** [comment]
Yup. Will take this one.

**Comment by arthurvr** [comment]
For jQuery.post this is already done: https://github.com/jquery/api.jquery.com/commit/4664f1ba316fb477915c8aea99ef0e2fdba88472.
