### ISSUE TITLE
.off(Event_object) isn't documented

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#384]
It looks like the entry from http://api.jquery.com/unbind/#unbind-event didn't get copied when `.off()` was created.

**Comment by AurelioDeRosa** [comment]
I've sent a PR (actually two, but please ignore the first) to add this info.

On a related note, I can see that the documentation of `unbind()` specifies the argument as <a href="http://api.jquery.com/Types/#Object"><code>Object</code></a>, but it should be <a href="http://api.jquery.com/category/events/event-object/"><code>jQuery.Event</code></a>, shouldn't it?

**Comment by dmethvin** [comment]
Yes, that should be `jQuery.Event` as well for `.unbind()`.
