### ISSUE TITLE
jQuery.ajax(), converters.

### ISSUE THREAD

**Issue by iSimonWeb** [jquery/api.jquery.com#385]
```<code />``` element that contains the default value for 'converters' is wider than its parent.
It can't go on a new line due to "white-space: pre" property.

**Comment by arthurvr** [comment]
Doesn't seem to be an issue for me:

![screenshot 2015-01-02 18 42 18](https://cloud.githubusercontent.com/assets/6025224/5598052/2952b722-92af-11e4-8a7a-85e69c6f2795.png)

Or it has been fixed, since this issue is open for years. Do you still experience this issue?
