### ISSUE TITLE
The unload docs have incorrect examples.

### ISSUE THREAD

**Issue by mzgol** [jquery/api.jquery.com#388]
The page under http://api.jquery.com/unload/ shows an example with `alert` which no longer works (in Chrome, Firefox) due to browser changes. The only allowed thing to do in the `beforeunload` handler are returning a string.

Originally reported as a jQuery bug: http://bugs.jquery.com/ticket/14559

**Comment by arthurvr** [comment]
@mzgol Just opened a PR: https://github.com/jquery/api.jquery.com/pull/639.
