### ISSUE TITLE
Dead end link for types "Tween" and "Anything"

### ISSUE THREAD

**Issue by Krinkle** [jquery/api.jquery.com#391]
https://api.jquery.com/animate/ contains:

> step
> Type: [Function](http://api.jquery.com/Types/#Function)( [Number](http://api.jquery.com/Types/#Number) now, [Tween](http://api.jquery.com/Types/#Tween) tween )

The link to http://api.jquery.com/Types/#Tween is a dead end as no such anchor exists on that page.

**Comment by arthurvr** [comment]
The `anything` type has been fixed in f0bfb23. Somebody who wants to take `tween`?

**Comment by arthurvr** [comment]
I didn't realise before, but we already have an issue about documenting tweens: https://github.com/jquery/api.jquery.com/issues/61.
