### ISSUE TITLE
Image error() handler example behaves incorrectly

### ISSUE THREAD

**Issue by theBRiGuy** [jquery/api.jquery.com#413]
http://api.jquery.com/error/

The example's intention is to assign the new missing.png src ONLY if the image loads with an error.

Actual result: It seems that the example given behaves incorrectly. The image "missing.png" will be assigned to the selector's attribute regardless of whether or not the image loaded with an error.

**Comment by kswedberg** [comment]
@dmethvin : at which version were shortcut event methods deprecated?

**Comment by dmethvin** [comment]
I'm pretty sure it was 1.9, but can't find the discussion.

**Comment by dmethvin** [comment]
Oh but it was just `.load()` and `.error()` which are strange and ambiguous.

**Comment by kswedberg** [comment]
ah, ok. thanks for that info!
