### ISSUE TITLE
Better Index Page

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/api.jquery.com#44]
The index page should provide an overview of the docs, mention which version the docs apply to, where to find older versions, link to intro tutorials on the learn site, etc.

**Comment by arthurvr** [comment]
> I created jquery/jquery-wp-content#278 to track the /category/all problem.

That issue was closed, so to go further on this right?

**Comment by arthurvr** [comment]
I just created a PR adding a brief note to the homepage: https://github.com/jquery/jquery-wp-content/pull/333.

**Comment by arthurvr** [comment]
I was recently working on finalizing my PR for this. It definitely needs some updates.

> Links to the changelogs and upgrade guides.

@scottgonzalez Is there some page with an overview of all release notes? I can't seem to find a page covering them all.

**Comment by scottgonzalez** [comment]
As far as I know, the core team has never done any changelogs or upgrade guides outside of blog posts, other than http://jquery.com/upgrade-guide/1.9/. So the only way to find them is to search through the blog history.
