### ISSUE TITLE
Global Ajax events work only with document

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#479]
Hello.
All the global Ajax event handlers have the following note:

> As of jQuery 1.8, the .ajaxStart() method should only be attached to document.

I want to focus on the word "should" which is not valid anymore. While this was true for jQuery 1.8, in newer versions of jQuery you can only listen for these events on `document`. Therefore the documentation should be updated with an integrative note (at least this is my opinion).

This issue is related with #118.

**Comment by AurelioDeRosa** [comment]
To fix this issue I propose to create a global note that is added to all Ajax global event. Any thoughts?

**Comment by dmethvin** [comment]
Agreed.

**Comment by arthurvr** [comment]
Sounds good to me :+1:
