### ISSUE TITLE
Arguments accessible by .always(), .done() and .fail() from jQuery.ajax()?

### ISSUE THREAD

**Issue by alano999** [jquery/api.jquery.com#49]
Now that .always(), .done() and .fail() are the preferred methods for implementing callbacks from a jQuery.ajax() invocation, and the old methods have been deprecated, it might be a good time to explain the arguments accessible by each of the new methods, and additionally the .then() and .pipe() when applied to jQuery.ajax() invocations?

When browsing the jQuery documentation on api.jquery.com, the available arguments are not listed anywhere, nor are they immediately obvious from elsewhere on the site.

Please would you consider improving the jQuery documentation - for the benefit of other developers who, like myself, cannot see how things work without delving into a debug session? Perhaps you could include the methods clearly within the listing of jQuery.ajax(), noting that the methods are implementations of Deferred and included here for clarity only?

Perhaps you could add a brief section immediately beneath the main properties/functions listing of jQuery.ajax(), showing definitively what arguments are available to each method's callbacks.  I am _guessing_ that the arguments are thus, and perhaps this is how they could be shown (once you have confirmed that my guesses are correct!)?:-

---

**_Methods**_ (part of _jqXHR_ and _Deferred_ implementations, shown here for clarity only)

**.ajax().always(function(a, textStatus, b){});**
Replaces method _.complete()_ which was deprecated in jQuery 1.8.
In response to successful transaction, arguments are same as .done() (ie. a = data, b = jqXHR) and for failed transactions the arguments are same as .fail() (ie. a = jqXHR, b = errorThrown).
This is an alternative construct for the complete callback function above. Refer to [deferred.always()](http://api.jquery.com/deferred.always/) for implementation details.

**.ajax().done(function(data, textStatus, jqXHR){});**
Replaces method _.success()_ which was deprecated in jQuery 1.8.
This is an alternative construct for the success callback function above. Refer to [deferred.done()](http://api.jquery.com/deferred.done/) for implementation details.

**.ajax().fail(function(jqXHR, textStatus, errorThrown){});**
Replaces method _.error()_ which was deprecated in jQuery 1.8.
This is an alternative construct for the complete callback function above. Refer to [deferred.fail()](http://api.jquery.com/deferred.fail/) for implementation details.

**.ajax().then(function(data, textStatus, jqXHR){}, function(jqXHR, textStatus, errorThrown){});**
Incorporates the functionality of .done() and .fail() methods.
Refer to [deferred.then()](http://api.jquery.com/deferred.then/) for implementation details.

**.ajax().pipe(function(data, textStatus, jqXHR){}, function(jqXHR, textStatus, errorThrown){});**
Incorporates the functionality of .done() and .fail() methods, allowing the underlying Promise to be manipulated.
Refer to [deferred.pipe()](http://api.jquery.com/deferred.pipe/) for implementation details.

---

My guesswork may be incorrect?  This perhaps illustrates the need to improve the documentation within jQuery.ajax().

Hope you can do something to improve documentation.

Kind regards,
Alan
(edited to note that .complete(), .error() and .success() have already been deprecated, and to explain the use of .then() and .pipe() with .ajax())

**Comment by axos88** [comment]
+1, it should be documented in the always, done, etc as well.

**Comment by Flimm** [comment]
+1

**Comment by xDaizu** [comment]
+1

**Comment by bperucchi** [comment]
1+

**Comment by sakkalabi** [comment]
Hi,
I will execute a script from ajax take ~ 20 min to get result in my website
jqXHR haven't option to show result after completed
[http://www.maisondemaroc.com](http://www.maisondemaroc.com)

**Comment by abhisina** [comment]
How can I test the fail scenario of post method.
I am using perl script for on server end.
I have already tried die, exit & return with multiple parameters but I always get success as status.

**Comment by dmethvin** [comment]
@abhisina That is a StackOverflow question.

**Comment by architchandra** [comment]
I'm a beginner, so might be wrong, but I am facing a lot of problems trying to understand how to use the methods related to $.ajax and deferred objects. At every step, I'm having to scour StackOverflow. The documentation on these fields is not well-suited for people who already don't have a thorough understanding. Would be grateful if fixed.

**Comment by leefogel** [comment]
:+1:

**Comment by damien-roche** [comment]
Save yourself the headache and use https://github.com/axios/axios
