### ISSUE TITLE
attr: Document attr(key, null) to remove attribute

### ISSUE THREAD

**Issue by Krinkle** [jquery/api.jquery.com#523]
Our unit tests cover it explicitly, and the code implements it explicitly:
```js
		if ( value !== undefined ) {

			if ( value === null ) {
				jQuery.removeAttr( elem, name );
```

From the API perspective I'd also say this makes a lot of sense as it allows roundtripping between the getter returning null and the setter receiving null.

**Comment by jugglinmike** [comment]
The discussion around the behavior of `attr` with `undefined`, while important, is unrelated to the intent of this issue. I think it should be safe to document "`null` unsets the attribute" even without consensus on `undefined`; is that right?

**Comment by Krinkle** [comment]
@jugglinmike Yep. My main request here is to document (and thereby acknowledge) that `null` is supported.

Right now, passing `null` can appear fragile. Peers sometimes point it out when I this idiom in code – sometimes expressing a (very understandable) preference for messy ternaries that switch between `attr()` and `removeAttr()` based on null. I don't want my code to be responsible for this switch. It inevitably leads to inconsistency when people forget to do so. For separation of concerns, this should be (and already is) in jQuery. I just want to make sure I can rely on this (without risking a silently breaking change), and to have API documentation that I can reference as proof of sorts when discussing it with others.

**Comment by Krinkle** [comment]
I still don't see this reflected on <https://api.jquery.com/attr/> ?

**Comment by kswedberg** [comment]
@Krinkle, yeah... https://github.com/jquery/api.jquery.com/issues/890 
sigh.
