### ISSUE TITLE
Incorrect data() api example in removeData() docs

### ISSUE THREAD

**Issue by ekuusela** [jquery/api.jquery.com#532]
>To avoid a re-query of the data- attribute, set the name to a value of either null or undefined (e.g. .data("name", undefined)) rather than using .removeData().

Calling data("name", undefined) doesn't modify the saved value.

**Comment by arthurvr** [comment]
This was fixed with https://github.com/jquery/api.jquery.com/commit/bb5a21d6215d229190182b52bd77ffc98d046e23.
