### ISSUE TITLE
Clarifying terminology

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#541]
Yesterday there was a discussion on the #jquery channel that I reported in [this gist](https://gist.github.com/AurelioDeRosa/9a6d565d68e09ea56db2) about the use of a correct terminology. In particular, a user asked about the correct term to refer to a method used upon a jQuery collection (like `$('p').each()`) vs the jQuery object (like `$.each()`), and how to refer to a jQuery collection/set.

I'm opening this issue to open a discussion and possibly collect feedback on this matter. Do you think the documentation needs to clarify the terminology? If so, somewhere in an existent page or in a new one?

**Comment by arthurvr** [comment]
> Can you provide an example of how this would come up where clear terminology is necessary?

Ping @AurelioDeRosa? I personally agree with @scottgonzalez last comment.
