### ISSUE TITLE
jQuery.on() for document fragment (off-DOM) already supported?

### ISSUE THREAD

**Issue by xorcus** [jquery/api.jquery.com#548]
Documentation for .on() method states in bold: "Event handlers are bound only to the currently selected elements; they ***must exist on the page*** at the time your code makes the call to .on()."

> Is this requirement for jQuery elements to be in DOM obsolete?

It seems that .on() works just fine for registering event handlers on document fragments created using jQuery, even before they are added into DOM. Of course, event won't be fired, but the call to .on() may take place before adding elements to DOM.

http://james.padolsey.com/stuff/jQueryBookThing/
The second half of the article also mentions this: "Among other things, this means that you can safely bind event handlers during element creation, and they will be added using jQuery's robust event mechanism. "

If this can be adopted as official jQuery support, could you please update the API docs?

[edit]
The same paragraph in .on() API docs ends with: "If ***new HTML*** is being injected into the page, select the elements and ***attach event handlers after the new HTML is placed into the page***. Or, use delegated events to attach an event handler, as described next."
So this also implies that content must be in-DOM

**Comment by Enelar** [comment]
I think this is important. Why it taked so long to fix?

**Comment by kswedberg** [comment]
Sorry about that, @Enelar . I'll post a fix in a few minutes.

**Comment by Enelar** [comment]
@kswedberg great work! Sorry about my mood.

**Comment by kswedberg** [comment]
:smile: No problem, @Enelar . I appreciated the nudge.
