### ISSUE TITLE
Callbacks.has() documentation should describe the signature with no parameters

### ISSUE THREAD

**Issue by jonathanbruder** [jquery/api.jquery.com#549]
`Callbacks.has()` (without parameters) returns true if the object has listeners and false otherwise. There are a few reasons that this behavior should be explicitly documented: 

* The general knowledge of the presence of listeners as frequently useful (in the creation of default behavior, for example)
* This signature is far more performant than the search for a specific listener
* State knowledge is more consistent with loose coupling than specific knowledge

Please add documentation for this signature. 

Examples might include a demonstration of this behavior before and after the use of the Callbacks.add and Callbacks.remove methods.

**Comment by arthurvr** [comment]
Assigned this to me, will take it this evening.

**Comment by jonathanbruder** [comment]
Thanks!

**Comment by arthurvr** [comment]
Looks like it's already done. That page already specifies the `callback` parameter is optional and has this in its `<desc>`:

> Determine whether or not the list has any callbacks attached.

**Comment by arthurvr** [comment]
Oh I've got it, https://github.com/jquery/api.jquery.com/commit/6f40df9ce96abfaca77f052b494102b302eac1a5 fixed this but somebody forgot to close this issue.

**Comment by kswedberg** [comment]
My mistake. Sorry about that, @arthurvr .
