### ISSUE TITLE
:checked selector does not work for select elements

### ISSUE THREAD

**Issue by jhfrench** [jquery/api.jquery.com#558]
On the ":checked Selector" page (http://api.jquery.com/checked-selector/), the description states:

"The :checked selector works for checkboxes, radio buttons, **and select elements**. For select elements only, use the :selected selector."

The :checked selector does not work on select elements. It works on the `option` children of select elements (see http://jsfiddle.net/jhfrench/mr7koj73/ for demonstration).

Suggest enumerating the destinction with this description:
"The :checked selector works for checkboxes, radio buttons, **and "selected" options of select elements**. For **the selected options of** select elements only, use the :selected selector."

I think it would also be a good idea to include a third example which illustrates using `:checked` with select/option elements.

**Comment by jhfrench** [comment]
I'm sorry to be a jerk, but this is still not correct at http://api.jquery.com/checked-selector/. Perhaps your changes did not get pulled back into the official jQuery repository?

**Comment by arthurvr** [comment]
@jhfrench You're true, the changes never got it into the repo, we needed to close the PR due to inactivity. Would you maybe like to submit a PR?

**Comment by jhfrench** [comment]
Ok, will do.

**Comment by arthurvr** [comment]
Thanks! Be sure to take a look at #616 and #562 before.

**Comment by arthurvr** [comment]
@jhfrench Still interested?

**Comment by jhfrench** [comment]
yes--putting it on my list to do today

**Comment by jhfrench** [comment]
I got a "failed" for the CLA--which I just signed. I've verified that my Git email addresses (j************@*******.com) is the same as I used to sign the CLA...

**Comment by arthurvr** [comment]
@jhfrench The problem is that your git config does not exactly match your CLA signature. You've got your middle name included in the signature and not in your git config. Resigning the CLA without your middle name should help.

**Comment by jhfrench** [comment]
Ok--signed the CLA again. How do I now clear that CLA error on my pull request?

While searching for how to clear the CLA tag, saw mention that ["only first signature is used"](https://github.com/jquery/jquery/pull/2243#issuecomment-97900456), so maybe this won't fixed the CLA error.

**Comment by jhfrench** [comment]
Looks like [CLA is ok now](https://github.com/jquery/api.jquery.com/pull/740#issuecomment-114901044)...ready to merge the PR?
