### ISSUE TITLE
setting css() value with "-=" might not work

### ISSUE THREAD

**Issue by yairEO** [jquery/api.jquery.com#575]
### Tested on:
- jQuery version `1.11.1`
- windows 7 64bit
- Firefox `32.0.3` and Chrome `37.0.2062.124 m`

### The problem:
This problem is specific when using `-=`. For example:

    $(document.body).css('paddingTop', '-=2001');

if the body has a `padding-top` value that is less than `2001` than this will do nothing. Expected result would be setting the `padding-top` to the minimum allowed, which is `0`.

Test page - http://jsbin.com/wanan/2/edit

The test page should be **red**. if it's **blue**, it means there is a bug. (I hope nobody who reads this is color-blind)

**Comment by arthurvr** [comment]
We can close this in favor of https://github.com/jquery/jquery/issues/1711, also this isn't an issue for the api docs.
