### ISSUE TITLE
Cloned elements dont keep user input values (select)

### ISSUE THREAD

**Issue by EntityB** [jquery/api.jquery.com#593]
Short story:
I wanted to modify user input values before submit, but I didnt want user to see. 
So, I cloned whole form with data and I did modifications on the clone. 
Later, I added select box, but it broke my widget. Few hours later I reallized cloned select dont know which value user selected. I belive correct behavior is, what jQuery user expects to happen. 

To make everything clear, I did small example: 

http://jsfiddle.net/v8d4zorc/

**Comment by arthurvr** [comment]
This isn't the appropriate place for support questions.
