### ISSUE TITLE
$.param() accepts a jQuery collection too

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#598]
I've just noted that the documentation of `$.param()` is incomplete as it doesn't mention that a jQuery collection is accepted as its first parameter. I haven't submitted a PR because I have no idea since what version it's possible.

**Comment by AurelioDeRosa** [comment]
Anyone has an idea of the version this possibility was introduced? I'd like to fix it.

**Comment by dmethvin** [comment]
Looks like jQuery 1.2. I'd just add `jQuery` to the list for the existing signatures, and add a sentence about it talking a jQuery object that should have inputs with name/value properties.
