### ISSUE TITLE
Deprecate use of plain objects

### ISSUE THREAD

**Issue by markelog** [jquery/api.jquery.com#600]
Since the last meeting it was decide to deprecate support for plain object as an argument.

like:

> jQuery( object )
object
Type: PlainObject
A plain object to wrap in a jQuery object.

/cc @gibson042 @dmethvin

**Comment by arthurvr** [comment]
So, what's the consensus in here?

**Comment by markelog** [comment]
@arthurvr will bring this up on today's meeting

**Comment by arthurvr** [comment]
@markelog Awesome, thanks!

**Comment by timmywil** [comment]
Per today's meeting, we're going to keep what we have and address problems on a case by case basis.
