### ISSUE TITLE
Change description of WrapAll with funarg

### ISSUE THREAD

**Issue by markelog** [jquery/api.jquery.com#605]
See discussion in https://github.com/jquery/jquery/issues/1843

**Comment by AurelioDeRosa** [comment]
I'm not sure what's the right thing to do here. Should we remove the function parameter from the 1.4 signature and add it as a jQuery 3.0 introduction? Or should we add a note discussing the issue?

**Comment by dmethvin** [comment]
I think a comment noting the changed behavior would be fine. The behavior is unchanged if there was just one element, and I suspect that's how most people were using it if at all.

**Comment by arthurvr** [comment]
>  The behavior is unchanged if there was just one element, and I suspect that's how most people were using it if at all.

I might be wrong but that's not entirely true. Prior to that commit we always passed the index `i`, even when there was only element.

**Comment by dmethvin** [comment]
True, although I doubt anyone depended on that. :smile:

**Comment by arthurvr** [comment]
@dmethvin @markelog WDYT about #745?

**Comment by arthurvr** [comment]
Closing as this is fixed in the v3 branch.
