### ISSUE TITLE
scrollTop() does not always return an Integer

### ISSUE THREAD

**Issue by michaelvk** [jquery/api.jquery.com#608]
While researching a very troublesome issue, I discovered that scrollTop() does not always return an Integer.

We were unable to replicate the issue, but believe it comes from some combination of the Articulate HTML5 viewer and some browser, or possibly from a PDF viewer embedded in an iFrame in an unnamed browser.

What we did see is that we had hundreds of errors where a value being posted directly to our server from the scrollTop() method that expected to receive an int value was receiving a float instead. We were able to nail down the issue by substituting a float for the scrollTop() value and seeing the exact same behavior in our server side code. When we replaced the scrollTop() value with Math.round(scrollTop value) the issue went away.

It is possible that the bug is actually in scrollTop(), not in the docs.

We are using jQuery.min, version 1.11.0, and did not see this error before we upgraded to jQuery 1.11.

**Comment by AurelioDeRosa** [comment]
Is this a valid issue? I'd really like to clean up a bit our issues list by closing old/irrelevant issues.

**Comment by dmethvin** [comment]
We didn't change any jQuery code, it's just that with subpixel resolution on some browsers it's possible for this to not be an integer. I think the action here would be to change the documented return value of `.scrollTop()` from Integer to Number.

**Comment by zcorpan** [comment]
FYI returning non-integer for `scrollTop` is according to the current spec, and since this has been shipping successfully it is unlikely to be reverted at this point.

https://drafts.csswg.org/cssom-view/#extension-to-the-element-interface
