### ISSUE TITLE
In " jQuery.map() "  documentation should "//code" be "http://code" ?

### ISSUE THREAD

**Issue by gitshub** [jquery/api.jquery.com#613]
The first example at http://api.jquery.com/jQuery.map/
contains the line

       script src="//code.jquery.com/jquery-1.10.2.js"></script

but unless I change that to 

       script src="http://code.jquery.com/jquery-1.10.2.js"></script

I get "ReferenceError: $ is not defined"

Is "//code" a valid URI ?  

( I use Firefox 34.0 on Linux Mint 17 )

**Comment by AurelioDeRosa** [comment]
I'm posting this note so that we can discuss it, but @paulirish in [this post](http://www.paulirish.com/2010/the-protocol-relative-url/) wrote:

> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.

So, perhaps we should specify the HTTPS protocol if it's available.

**Comment by gnarf** [comment]
no objection to switching to https everywhere for it.  I think we can do
that (relatively) easy, I just don't remember how

**Comment by arthurvr** [comment]
If we're going to switch them all to https, which I'm +1 on, we should also change other things than the script tags. [Iframes, for example.](https://github.com/jquery/api.jquery.com/blob/a3cc9b422c5c245a1f334f65de82275dda048084/entries/contents.xml#L58)

@konklone Thanks for both the PRs you opened!

**Comment by agcolom** [comment]
Yes, I'm happy about that change also. Should we discuss this at our Content meeting on wednesday to agree a way forward? @gnarf @arthurvr @danheberden @AurelioDeRosa

**Comment by AurelioDeRosa** [comment]
:+1: on discussing this topic further in the meeting.
