### ISSUE TITLE
$.post(url, vars, function(){}) improperly encoding variable names with ( and )

### ISSUE THREAD

**Issue by centerionware** [jquery/api.jquery.com#614]
When submitting a post using this following (Typed on the fly) example:
namemap = new Object();
namemap["some name with ()"] = "somedata";
$.post(url, vars, function(){})
The ()'s are not being properly encoded to %28 and %29 respectively. I believe it may be using encodeURIComponent instead of encodeURI.
When submitting a form using a standard post, they are encoded.

JQuery version 1.11.1 from http://code.jquery.com/jquery-1.11.1.js

**Comment by kswedberg** [comment]
Regardless of whether there is a problem with improper encoding, I don't see how it is a documentation issue. I'm pretty sure this is the wrong repo for submitting this bug report.

**Comment by 0xdeadc0de** [comment]
It's not about documentation, it's about using encoding functions that don't fully encode to modern standards. I was just trying to point out that encodeURI in modern chrome does encode to rfc3986, while encodeURIComponent encodes only to rfc2396, and jquery uses encodeURIComponent for encoding variable names and values, which is causing inconsistent behavior when using jquery to submit a post vs not using any javascript at all. 
Where else would I post about it? It's jquery that's calling the encode functions, not any other project.

**Comment by kswedberg** [comment]
The jQuery project has many repos. This is the repo for the API documentation (api.jquery.com). The repo for jQuery core is at https://github.com/jquery/jquery

**Comment by 0xdeadc0de** [comment]
well, don't I feel stupid. sorry about that!

**Comment by kswedberg** [comment]
@0xdeadc0de : No problem at all. Honest mistake.
