### ISSUE TITLE
Clarify use of .html() for <script> tags

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#618]
<p>To set the content of a &lt;script&gt; element, which does not contain HTML, use <code>.text()</code> and not <code>.html()</code>.</p>

**Comment by AurelioDeRosa** [comment]
Hi @dmethvin. Is the text you've reported the one to include or a suggestion  that has to be expanded?

**Comment by dmethvin** [comment]
That's my suggested text based on the problem the person reported. I think it could go in there somewhere verbatim.

**Comment by arthurvr** [comment]
> Is the text you've reported the one to include or a suggestion that has to be expanded?

Maybe add a little note explaining why it won't work too.

**Comment by arthurvr** [comment]
I just opened #675. @dmethvin Would you mind reviewing?
