### ISSUE TITLE
Categories for focus events inconsistent

### ISSUE THREAD

**Issue by arangas** [jquery/api.jquery.com#619]
It looks like the categories for focus events are inconsistent, but I'm not sure what they should be:

* [.focus()](http://api.jquery.com/focus/): Events > Form Events | Forms
* [.blur()](http://api.jquery.com/blur/): Events > Form Events | Forms
* [.focusin()](http://api.jquery.com/focusin/): Events > Form Events
* [.focusout()](http://api.jquery.com/focusout/): Events > Keyboard Events | Events > Mouse Events

**Comment by AurelioDeRosa** [comment]
Anyone has a good proposal for how to organize them? // cc @agcolom @arthurvr

**Comment by dmethvin** [comment]
Looking at how the events are generally used and where people are likely to look, I'd say `.focus()` and `.blur()` are doing it right. Technically [any element can be play the focus game](http://www.w3.org/TR/DOM-Level-3-Events/#events-focusevent-doc-focus) though, by either mouse or keyboard. You just have to [set a `tabindex`](http://www.w3.org/TR/html5/editing.html#focus-management) on the element. But the categories for `.focusout()` are just nutty.

**Comment by arangas** [comment]
Would you like a PR for changing all of these to Events > Form Events | Forms?

**Comment by arthurvr** [comment]
@arangas Sure. PR welcome! Be sure to [sign the CLA](http://contribute.jquery.org/CLA/).
