### ISSUE TITLE
New 3.0 $.get(Object) and $.post(Object) signatures

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#620]
See https://github.com/jquery/jquery/issues/1986 and https://github.com/jquery/jquery/issues/1995 for more detail. We'll also updates to the docs for [$.get](https://github.com/jquery/api.jquery.com/blob/master/entries/jQuery.get.xml) and [$.post](https://github.com/jquery/api.jquery.com/blob/master/entries/jQuery.post.xml) adding a new signature for `Object` effective as of jQuery 3.0 You can probably get what you need from the [$.ajax](https://github.com/jquery/api.jquery.com/blob/master/entries/jQuery.ajax.xml) docs entry.

**Comment by arthurvr** [comment]
For the reference, PR https://github.com/jquery/api.jquery.com/pull/622.

**Comment by AurelioDeRosa** [comment]
@arthurvr I'm resurrecting this issue because it was merged in master, thus already published. However, this should be in the jQuery 3.0 branch.

**Comment by arthurvr** [comment]
@AurelioDeRosa Yes, you said that in a comment on the commit as well. It's worth reverting IMHO.

**Comment by AurelioDeRosa** [comment]
Oh...really? Sorry about that @arthurvr, I'm getting old :)

**Comment by timmywil** [comment]
Will actually be added in 1.12/2.2. I've fixed it in a [branch](27de1d526e42135bf801a68edcb5d3933d6822c8).
