### ISSUE TITLE
why http://api.jquery.com/ not update

### ISSUE THREAD

**Issue by feiwen8772** [jquery/api.jquery.com#628]
why http://api.jquery.com/ not update

**Comment by scottgonzalez** [comment]
Sorry, but that isn't a question we can answer. The site is updating just fine. If you have an actual question, please provide details about what you think is wrong.

**Comment by phIE9** [comment]
@scottgonzalez Site isn't updating fine. Look at this commit https://github.com/jquery/api.jquery.com/commit/95a9b6591549cec0e1b07b8ee6baa1d625071262 it does not appear online. first check and then close issue please thanks

**Comment by scottgonzalez** [comment]
It will update on the next deployment.

**Comment by RedWolves** [comment]
All commits made to master are auto deployed to the staging site so in this repos case http://stage.api.jquery.com.

At some point a repo maintainer will tag the repo and that will deploy to the production server. 

You can find out more about how the sites work on the Contribute site http://contribute.jquery.org/web-sites/#deploying-to-staging-and-production-environments

**Comment by kswedberg** [comment]
The problem yesterday was that it did not deploy to the production server after I tagged the repo because I pushed two tags at the same time, choking the deploy script (as @scottgonzalez explained to me in #jquery-content). That little snafu was resolved when @arthurvr pushed another tag later in the day.

**Comment by RedWolves** [comment]
@kswedberg are we going to have to flog you ... again?

**Comment by kswedberg** [comment]
:smiley_cat:
