### ISSUE TITLE
Correct IE note on removeAttr page 

### ISSUE THREAD

**Issue by markelog** [jquery/api.jquery.com#642]
Talking about this one - 

> Note: Removing an inline onclick event handler using .removeAttr() doesn't achieve the desired effect in Internet Explorer 6, 7, or 8. To avoid potential problems, use .prop() instead:

Aside of removing Internet "Explorer 6, 7" for 3.0, it should include 9 and 11, but not 10.

**Comment by arthurvr** [comment]
@markelog I opened #652, could you review?

**Comment by arthurvr** [comment]
Merged in https://github.com/jquery/api.jquery.com/commit/3cec29b10bd01699cbd5973f87a6514c18073e23. GitHub didn't close the PR/issue since it's merged into the v3 branch, not master.
