### ISSUE TITLE
404 on http://api.jquery.com/jQuery.map

### ISSUE THREAD

**Issue by gibson042** [jquery/api.jquery.com#644]
Unlike most pages, http://api.jquery.com/jQuery.map/ requires the trailing slash instead of making itself available by redirect. This is almost certainly because `.map` is a plausible extension, but we should still enable the convenient path if it's not too much trouble.

**Comment by scottgonzalez** [comment]
@nacin Any ideas on this?

**Comment by gnarf** [comment]
Fixed in the nginx configs

**Comment by arthurvr** [comment]
Thanxxx @gnarf!
