### ISSUE TITLE
toggle(bool) - What to call the bool argument?

### ISSUE THREAD

**Issue by gnarf** [jquery/api.jquery.com#655]
This came up over in #654 - People seem to like our old name `showOrHide` more than the new version called `setShown`.  I really wasn't expecting anyone to be against the rename, so I merged it anyway.  We can always change it back, or find something better, so lets take some time to really think about what this should be called:

http://api.jquery.com/toggle/#toggle-setShown

My personal arguments are roughly paraphrased from the original argument in #654:

* `setShown` seems to evaluate when read (as english) to the actual purpose, "set shown true" means "show" and "set shown false" means "hide"

* What exactly does `showOrHide` "false" mean? or for that matter "true"?

* One benefit I see to sticking with `showOrHide` is that the deep link to the method with that argument reads a little better. http://api.jquery.com/toggle/#toggle-showOrHide

cc @kswedberg @AurelioDeRosa who spoke up in the other issue.

**Comment by dcherman** [comment]
`shouldBeShown`?

**Comment by gnarf** [comment]
I like `shouldBeShown` for the same reasons, `setShown` feels "shorter" but either is better than `showOrHide` IMO

**Comment by kswedberg** [comment]
how about `display`? that works with true / false, and it also has a nice deep link: http://api.jquery.com/toggle/#toggle-display

**Comment by gnarf** [comment]
I worry that might be "overloaded" a bit much in JS/CSS land, but I like it - "display true/false" works for me too (at least way better than "show or hide true/false" does)

**Comment by burka** [comment]
@kswedberg I think `display` is quite good :-) `toggle(display)` explains quite a lot and would be easy to understand on first sight.

I would tend to something like `show(shown)` ( and maybe, but not so much preferred `hide(hidden)`) if it wouldn't mess up so much. 

If it is to short or not meaningful enough I would suggest `showIfTrueElseHide` - almost the same as `showOrHide` *but* it will help you to understand its meaning.

**Comment by AurelioDeRosa** [comment]
Hi @gnarf, and thank you for opening this issue. I think the proposal of @kswedberg fits well: pretty clear name and nice deep link. Perhaps `doDisplay` would be even clearer? What do you think?

**Comment by arthurvr** [comment]
I'm +1 for `doDisplay`. If everybody is alright with that I can submit a PR.

**Comment by kswedberg** [comment]
I'm not a fan of `doDisplay`, but I admit it's purely a matter of taste. So, if @gnarf is :+1: for `doDisplay`, let's do it.

**Comment by arthurvr** [comment]
Well then, it's up to you @gnarf. What do you think?

**Comment by gnarf** [comment]
I think I still like 'display' best. We call out the valid values so you
won't think 'none' is what you want to hide...

**Comment by burka** [comment]
I think `display` is the best known option. :+1:

**Comment by arthurvr** [comment]
Seems like `display` it is. Will submit PR.

**Comment by arthurvr** [comment]
@kswedberg @gnarf I just opened #666, one of you who wants to review?
