### ISSUE TITLE
Can we remove our silly JSON.stringify polyfill from examples?

### ISSUE THREAD

**Issue by gnarf** [jquery/api.jquery.com#658]
http://caniuse.com/#search=json - support back to IE8

The example in `jQuery.extend()` has a pretty complex "fake stringify" method and seems overly complex for todays needs.  https://github.com/jquery/api.jquery.com/blob/03fcbfbd17b494cc1122b6727adfcd8101b0ea9b/entries/jQuery.extend.xml#L59

**Comment by arthurvr** [comment]
I wouldn't do it in master yet, as people might just copy-paste and be confused because jQuery 1.x is compatible with IE6+. That being said, I think we can just do this in the `v3.0.0-docs` branch, as there we don't have to support IE8 anyways.

**Comment by arthurvr** [comment]
I can PR if everybody agrees.

**Comment by gnarf** [comment]
We could also just use http://api.jquery.com/jQuery.param/ instead?  I just
want to simply the example...

**Comment by arthurvr** [comment]
JSON is a little more readable IMHO, but fine with that as well.

**Comment by gnarf** [comment]
I Agree that JSON is indeed more readable... I just don't think that JSON
encoder we have in the example is at all readable, and it confuses the
examples quite a bit to try and parse it.

**Comment by arthurvr** [comment]
PR gh-661.
