### ISSUE TITLE
Returning elements in DOM order is not documented

### ISSUE THREAD

**Issue by fenduru** [jquery/api.jquery.com#659]
As of [jQuery 1.3.2](http://blog.jquery.com/2009/02/20/jquery-1-3-2-released/) elements are returned in DOM order (which is a useful feature). This is not documented anywhere that I could find on api.jquery.com though.

It is, however, documented on the [sizzle wiki](https://github.com/jquery/sizzle/wiki)

**Comment by timmywil** [comment]
> How about if we document this in the jQuery() page by expanding on that note above, plus add a similar sentence in the Types page?

:+1:

**Comment by fenduru** [comment]
FWIW when I checked to see if this was documented I looked here:

http://api.jquery.com/category/selectors/

**Comment by timmywil** [comment]
Selector syntax is still a different category for the most part, unless you're talking about multiple selectors. In which case, it's already documented [there](http://api.jquery.com/multiple-selector/):

> The order of the DOM elements in the returned jQuery object may not be identical, as they will be in document order.

**Comment by karan1276** [comment]
Hey guys,

I am new to this world of open source development, I wanted to get involved with jQuery. I read contribute.jquery.org and also talked to devs at jQuery IRC channel #jquery.

All of them told me to start with documentation first because lots of work needs to be done there and its relatively easier :)

So here I am, can i work on this issue? what say @fenduru @dmethvin @timmywil ?

Thanks

**Comment by arthurvr** [comment]
That's awesome to hear, @karan1276! We :heart: contributions!

> All of them told me to start with documentation first because lots of work needs to be done there and its relatively easier :)

We can use help everywhere but if you're willing to work on documentation that rocks! Thanks!

> So here I am, can i work on this issue? what say @fenduru @dmethvin @timmywil ?

Nobody is working on this yet, so, yes you can! Don't hesitate to ask us any questions here or in `#jquery-dev` or `#jquery-content` on IRC.

**Comment by AurelioDeRosa** [comment]
Closing this issue as it has been fixed.
