### ISSUE TITLE
.after( Integer index, String html ) documentation

### ISSUE THREAD

**Issue by jcuenod** [jquery/api.jquery.com#663]
There are two ".after( function )" functions listed at http://api.jquery.com/after/ but the second (added in v1.10) is missing the second parameter (as in title). It seems that the description is fine.

**Comment by AurelioDeRosa** [comment]
Hi @jcuenod, I think everything is fine. It's not `after` that has two arguments (the callback and a string), but the callback function passed to `after` that, starting from version 1.10, receives a second argument.

**Comment by jcuenod** [comment]
Humblest apologies, you are correct.
