### ISSUE TITLE
.on() - add note about not being able to remove a listener during the event

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#665]
From https://github.com/jquery/jquery/issues/2094

> My suggested resolution is just to add a sentence to the .on() docs clarifying that the handler list for an element is set when the event is first delivered.

**Comment by AurelioDeRosa** [comment]
I don't have the privileges to assign this issue to myself, so I'm posting this message to let you know that I'm working on it.

**Comment by arthurvr** [comment]
@AurelioDeRosa Thank you!

**Comment by arthurvr** [comment]
PR #670
