### ISSUE TITLE
Add a temporary note due to a libxml2 bug

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#667]
Due to [this libxml2 bug](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=766884) introduced in the last version (2.9.2) the command `grunt deploy` fails. Should we add a (temporary?) note?

**Comment by arthurvr** [comment]
Is this really an issue many people are running into? Givin the fact that nobody reported this earlier, I don't think so.

**Comment by AurelioDeRosa** [comment]
The bug was reported only 3-4 months ago. Considering that not many people build the content websites locally, I think it's plausible.

**Comment by arthurvr** [comment]
@scottgonzalez @kswedberg What are your thoughts about this? I personally feel like this isn't something we should be including.

**Comment by kswedberg** [comment]
I don't think it's worth it.

**Comment by scottgonzalez** [comment]
I'd prefer trying to find a way to detect it directly in the code so we can print nicer error messages.

**Comment by arthurvr** [comment]
> I'd prefer trying to find a way to detect it directly in the code so we can print nicer error messages.

That's definitely a good idea. Does that mean we need to move this issue over to grunt-jquery-content then?

**Comment by scottgonzalez** [comment]
As far as I can tell, this has no effect on us. We don't use `--noent` for `xmllint` and we don't have any `<!ENTITY>` elements.

**Comment by AurelioDeRosa** [comment]
I know that one case doesn't mean a bug, but I had to use the previous version to have a working environment.

**Comment by scottgonzalez** [comment]
So perhaps file an issue with the proper details?
