### ISSUE TITLE
Replace GnuWin32 link

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#668]
A while ago a user reported us an issue (#71) that caused the build to fail on Windows. @kswedberg fixed the documentation by updating the link with commit 6559302856cf3fecefa319d3d7ce1877c694b41b. The link was then changed again by @scottgonzalez with commit 04f42c47bfa8a3236b76dd69a332359384a1a4b5. However, I had the same issue of the user and ended up using the files at http://www.zlatkovic.com/libxml.en.html.

So, do you agree that we should replace the GnuWin32 link?

**Comment by scottgonzalez** [comment]
Yes, but this will need to happen in all of the API repos. Are you interested in sending a PR for all of them? If not, I can get them all updated.

**Comment by AurelioDeRosa** [comment]
I can submit a PR for every API repo @scottgonzalez. However, if you want to take care of this issue, go ahead. Let me know what works best for you.

**Comment by arthurvr** [comment]
While we're on it, I'm actually wondering if this info needs to be in the readme. Why don't we link up [the contribution guides](http://contribute.jquery.org/web-sites/) and maintain only one version?

**Comment by arthurvr** [comment]
I just opened a PR for this repo: #676. I will do it for every repo once this one is merged.
