### ISSUE TITLE
Selectors :hidden/:visible are slow and can force layout

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#679]
Need to add a note to the `:visible` and `:hidden` selector pages to the effect of:

> Using this selector heavily may cause performance issues because it can force the browser to re-render the page in order to determine visibility. Tracking the visibility of elements via other methods, for example a class name, can provide better performance.

There were some other optimizations [recently made in Sizzle](https://github.com/jquery/jquery/issues/2042) that improved performance but it still can be expensive.

**Comment by dmethvin** [comment]
Ref https://github.com/jquery/jquery/issues/2108

**Comment by arthurvr** [comment]
#682 :)
