### ISSUE TITLE
jQuery.merge: add note about it correcting the `length` property

### ISSUE THREAD

**Issue by arthurvr** [jquery/api.jquery.com#686]
> Internally we use jQuery.merge to merge jQuery objects which are array-like so they need to have length corrected. I see it's not documented at http://api.jquery.com/jQuery.merge/ so perhaps an API ticket is needed (cc @arthurvr)

https://github.com/jquery/jquery/issues/2155

**Comment by mzgol** [comment]
This is documenting currently undocumented behavior so I'd like @jquery/core to approve it first.

**Comment by markelog** [comment]
We say that `merge` excepts arrays not `array-like`s, therefore we would need to get funky of explaining why jquery corrects the length.

Do we need to document that? Essentially, we would be documenting `array-like`s as acceptable arguments, if user uses `merge` correctly, their wouldn't even know about that side-effect.

**Comment by mzgol** [comment]
> Do we need to document that? Essentially, we would be documenting array-likes as acceptable arguments, if user uses merge correctly, their wouldn't even know about that side-effect.

The problem is `jQuery.merge` is public and de facto accepts array-likes; people use it to e.g. merge with the `arguments` object. So we might as well document this behavior, I doubt it'll ever change.

**Comment by timmywil** [comment]
> we might as well document this behavior, I doubt it'll ever change.

Agreed. However, although we use this term in [several places already](http://api.jquery.com/?s=array-like), I think we should document what exactly "Array-like" means, perhaps [on the types page](http://api.jquery.com/Types/#Object).

**Comment by mzgol** [comment]
@timmywil Good idea.

**Comment by arthurvr** [comment]
Once the Array-like type lands to the types page I can update this PR. Thanks for the suggestions you all!
