### ISSUE TITLE
jQuery.unique() removes duplicated numbers and strings

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#695]
It's well known that [jQuery.unique()](http://api.jquery.com/jQuery.unique/) works with arrays of DOM elements and not arrays of strings and numbers. This is also highlighted by the documentation page:

> Note that this only works on arrays of DOM elements, not strings or numbers.

However, it **does** work with arrays of numbers and strings as well ([proof](http://jsfiddle.net/j8cq841g/)).

So, either the documentation should be updated or this feature is intentionally secret for possible future changes.

**Comment by timmywil** [comment]
I'd rather not guarantee that `jQuery.unique` work with number/strings, even if it does right now. That particular function has gone through many revisions and we've only ever focused on sorting nodes in document order and removing the duplicates there. If we had to support numbers and strings as well in future revisions, it could cause serious headache.

**Comment by AurelioDeRosa** [comment]
What do you think about adding a note about this in the doc @timmywil?

**Comment by timmywil** [comment]
Maybe something like "this method may work with numbers and strings, but is not supported"?

**Comment by timmywil** [comment]
and may break in future versions.

**Comment by arthurvr** [comment]
> this method may work with numbers and strings, but is not supported

If something isn't supported it should not even be mentioned IMHO.

> What do you think about adding a note about this in the doc @timmywil?

From the moment we start telling people it works we'll have to support it for like... always. Plus people might run into rough edges like the `[NaN, NaN]` case. Cc'ing @gibson042 @dmethvin but I'm :-1:.

**Comment by AurelioDeRosa** [comment]
@timmywil Yes, I was thinking about something like that.

@arthurvr I don't think a note that asserts **not** to use the method with numbers and strings forces us to support that feature. Also, it has the advantages of avoiding people reporting the same issue again.

**Comment by scottgonzalez** [comment]
It actually doesn't work with numbers. `[1, 5, 3, 99, 2, 6, 9]` is most certainly not sorted.

**Comment by AurelioDeRosa** [comment]
@scottgonzalez not sorted but with the duplicates removed as the title states.

**Comment by dmethvin** [comment]
The docs seem pretty clear to me right now:

> This function only works on plain JavaScript arrays of DOM elements, and is chiefly used internally by jQuery. You probably will never need to use it.

There are certainly other cases that might work, but the docs don't guarantee it nor should they.

**Comment by gibson042** [comment]
I agree with @dmethvin; the documentation is decent as-is and DOM nodes are the only valid input... behavior for invalid input is, as always, undefined.
