### ISSUE TITLE
Incorrect information for the selector property

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#696]
In the documentation of the [`selector` property](http://api.jquery.com/selector/) we assert that it was removed in jQuery 1.9. However, this is not true as it's still available in versions 1.11 and 2.1, and it'll be removed in jQuery 3.0 ([issue #1908](https://github.com/jquery/jquery/issues/1908)).

**Comment by dmethvin** [comment]
In 1.9 it was [neutered](https://github.com/jquery/jquery/pull/1006) in that most of it was removed and only a small amount of the previous functionality was left behind. I agree we should change the "removed" to 3.0 though. That page is pretty ugly in general and could use some paragraph breaks!

**Comment by arthurvr** [comment]
Will do it.

**Comment by arthurvr** [comment]
Fixed in v3 branch.
