### ISSUE TITLE
wrap() uses the first element when provided a jQuery object

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#698]
The documentation of the [`wrap()`](http://api.jquery.com/wrap/) method asserts that a jQuery object or a string containing a selector can be passed as an argument. However, in case a selector matching more than one element or a jQuery object containing more than one element is passed, only the first (element) is used as the wrapper.

This detail is not specified and I think it's worth to add it. Any thoughts?

**Comment by dmethvin** [comment]
Seems like a good idea. I don't know that I've ever seen it used with a selector to be honest!

**Comment by arthurvr** [comment]
:+1: https://github.com/jquery/api.jquery.com/pull/700.
