### ISSUE TITLE
Create an "Array-Like" type

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#708]
As suggested by @timmywil in https://github.com/jquery/api.jquery.com/issues/686#issuecomment-90646439, add an "Array-Like" type to our Types page to clarify when a method accepts more than just `Array`. Perhaps something like this:

> **Array-Like** - Either a true JavaScript `Array` or a JavaScript `Object` that contains a numeric `length` property. This latter case includes array-like objects commonly encountered in web-based code such as the `Arguments` object and the `NodeList` object returned by many DOM methods. Note that when a jQuery API accepts either plain Objects or Array-Like objects, a plain Object with a numeric `length` property will trigger the Array-Like behavior.

**Comment by arthurvr** [comment]
Yup, :+1:. I'll take this one.
