### ISSUE TITLE
jQuery(): add note about support of text nodes

### ISSUE THREAD

**Issue by arthurvr** [jquery/api.jquery.com#709]
The default assumption should be that text nodes aren't supported by our APIs. We should add a note about it in the "using dom elements" section. Discussion started over at https://github.com/jquery/api.jquery.com/pull/592.

Perhaps we should also add it to `.contents()` which is another place where text nodes can sneak in.

**Comment by arthurvr** [comment]
@pcj We're, as mentioned in the PR, still interested in hearing how the text node ended up in the collection.

**Comment by arthurvr** [comment]
Would we be okay with explicitly saying something like

> Please note that you can pass text nodes into a jQuery collection this way, although, the default assumption should be that jQuery doesn't support manipulations on text nodes. The few APIs that support text nodes will have an explicit note about that on their API documentation     page.

on the `jQuery()` entry?

**Comment by gibson042** [comment]
:+1: I like that a lot, but "manipulations" is overloaded in this context. "Operations" might be better, or explicitly mentioning the modules (is there anything other than traversing and filtering?).

**Comment by arthurvr** [comment]
@gibson042 I totally agree. PR: https://github.com/jquery/api.jquery.com/pull/738. Mind taking a look and giving your LGTM if you like it?

**Comment by timmywil** [comment]
Could we include comment nodes here? I think they mostly receive the same treatment as text nodes. See https://github.com/jquery/jquery/issues/2309.
