### ISSUE TITLE
Specify how to detach `dblclick()` event handler

### ISSUE THREAD

**Issue by jhfrench** [jquery/api.jquery.com#717]
The documentation at https://api.jquery.com/dblclick/ describes how to attach the `dblclick()` method.

Unlike other event listener bindings, like [`on()`](https://api.jquery.com/on/#entry-longdesc), [`bind()`](https://api.jquery.com/bind/#entry-longdesc), [`delegate()`](https://api.jquery.com/delegate/#entry-longdesc), and [`live()`](https://api.jquery.com/live/#entry-longdesc) the `dblclick()` documentation does not specify the best way to *remove* the binding (ie, *"To remove events bound with .on(), see .off()."*).

I assume, based on the "This method is a shortcut for .on( "dblclick", handler)..." note, that the correct way to detach the `dblclick()` event listener is to use `off("dblclick")`.

**Comment by arthurvr** [comment]
Going to wait for other feedback, but I don't think it's needed. Other shorthand methods, such as `click`, don't mention this as well. I think if that's possible we should avoid unnecessary things and keep the pages as slim as possible (definitely pages for shorthand methods).

That said, the pages states that `.dblclick()` is shorthand for `.on()` and on the `on()` entry it is actually explained.

**Comment by jhfrench** [comment]
@arthurvr Understood.

That said, I'm making this suggestion becaues I have encountered some ambiguity about the best way to detach `dblclick()`; I came across this issue while maintaining code which used `unbind()`.

For the same reasons it is useful to link `off()` with `on()`, it it is useful to link `off()` with the `on()` shorthand children like `dblclick()`, `click()`, etc--*particularly for jQuery newbies* who can be understood to need explicit guidance.

**Comment by arthurvr** [comment]
> particularly for jQuery newbies who can be understood to need explicit guidance.

That sentence makes me think it's more likely something we need to clarify on learn.jquery.com. WDYT?

**Comment by dmethvin** [comment]
Also, I think of the "shorthand" attachment methods as archaic, it's better to use `.on()` and `.off()` for everything so this kind of confusion doesn't happen in the first place. If people agree perhaps we could just add a reusable note to all of them. Since the method name is the event name, we should be able to use some of that funky XML templating magic to put in the note that @jhfrench is asking to add?

**Comment by arthurvr** [comment]
> Since the method name is the event name, we should be able to use some of that funky XML templating magic to put in the note that @jhfrench is asking to add?

Yup, that's definitely no problem.

**Comment by kswedberg** [comment]
+:100: to reusable note, @dmethvin

**Comment by arthurvr** [comment]
There we go: https://github.com/jquery/api.jquery.com/pull/719. Feedback welcome ;)

**Comment by jhfrench** [comment]
Sweet. Love it. Thanks.
