### ISSUE TITLE
$.trim converts to string an array and apply the trim to the string converted

### ISSUE THREAD

**Issue by patrixd** [jquery/api.jquery.com#718]
Hi.

I'm not sure if that behaviour will be change or not in the future. Because the documentation don't tell anything about the convertion to string the input, and the tests does not include any case with an array.

Can I use $.trim with an array and be sure that the result will be allways the trim of the concatenated elements?

Example: http://fiddle.jshell.net/patrixd/xgtgrgkj/2/

Thanks a lot.

**Comment by arthurvr** [comment]
> Because the documentation don't tell anything about the convertion to string the input, 

Passing a method 'invalid' input (docs say it should be a string) will always be undefined behaviour.

> Can I use $.trim with an array and be sure that the result will be allways the trim of the concatenated elements?

No, you can't. For now this is not an officially supported behaviour, and I don't think it should become one. For now you should just consider it as a funny side effect. `trim()` takes a string, not an array, and thus this is undefined behaviour.

Also, please note that it does not exactly concatenate, it adds a comma between the items. For example:

```js
$.trim( [ 'foo', 'bar' ] ); // foo,bar
```

I don't see any use case for that, do you?

Waiting for other feedback, but I'm :-1:. Also, there are no unit tests so for now we can't change anything to the API site at the moment.

**Comment by patrixd** [comment]
Ok, thanks for your quick answer. My main question is if I can use it with an array. 

You are right it is a funny side effect. :laughing:

**Comment by dmethvin** [comment]
Definitely don't use the API in undocumented ways, because it is likely to break in the future. If you have doubts, it's a good idea to ask like you did here. Better safe than sorry.

**Comment by Krinkle** [comment]
@patrixd If you need that behaviour, use this instead:

```js
var data = [ "  a", 2, "  b  ", "c;  " ];
$.trim( data.join( ',' ) );
> "a,2,  b  ,c;"
```

This produces the same result, but makes a string explicitly (using Array#join) before passing the value to jQuery's trim.

**Comment by arthurvr** [comment]
+1 to what @Krinkle said. I think we all agree this shouldn't be officially supported or am I wrong?

**Comment by patrixd** [comment]
Yes @Krinkle I will use something like that. Thanks a lot.
