### ISSUE TITLE
Incorrect example in api.jquery.com/empty/

### ISSUE THREAD

**Issue by eduard-malakhov** [jquery/api.jquery.com#720]
In the following code sample (the one following text "This will result in a DOM structure with the Hello text deleted:") the 2nd line must not be present, since it shows the result of applying $( ".hello" ).empty().

    <div class="container">
      <div class="hello"></div>
      <div class="goodbye">Goodbye</div>
    </div>

The correct example would be

    <div class="container">
      <div class="goodbye">Goodbye</div>
    </div>

**Comment by AurelioDeRosa** [comment]
The example is correct.[ `empty()`](http://api.jquery.com/empty/) only removes the child nodes, not the element itself. If you want to remove the element as well, you should use [`remove()`](http://api.jquery.com/remove/).

**Comment by eduard-malakhov** [comment]
I see, my mistake. I thought that the two examples are exactly the same. Didn't notice that 'hello' was actually gone.
