### ISSUE TITLE
The name of file next-adjacent-Selector.xml

### ISSUE THREAD

**Issue by yanxyz** [jquery/api.jquery.com#722]
In recent two days I try to parse the docs and encounter two slight "problem":

1. The name of file next-adjacent-Selector.xml, the first letter of the word "Selector" is uppercase, while other slectors file is lowercase. Is this a typo?
2. The file offsetParent.xml doesn't have version in the `category` tag.

**Comment by arthurvr** [comment]
> The name of file next-adjacent-Selector.xml, the first letter of the word "Selector" is uppercase, while other slectors file is lowercase. Is this a typo?

You're right on that one. PR opened to fix it: #723.

> The file offsetParent.xml doesn't have version in the category tag.

Another PR: https://github.com/jquery/api.jquery.com/pull/724

-

Thanks for reporting this!
