### ISSUE TITLE
Api for jQuery.post() shows "version added: 3.0"

### ISSUE THREAD

**Issue by ltongues** [jquery/api.jquery.com#725]
![screenshot from 2015-04-28 20 21 27](https://cloud.githubusercontent.com/assets/7702679/7375890/4b40b7b8-ede4-11e4-9b45-be77cb0182cc.png)

**Comment by dmethvin** [comment]
That information is actually correct, that particular signature won't be available until 3.0 ships. However it would be better to put the new signature after the old one, since that is the one most people will be seeking.

**Comment by arthurvr** [comment]
> However it would be better to put the new signature after the old one, since that is the one most people will be seeking.

Yep, agreed, assigning to me :) Hope I'll have some time to do this this evening.

**Comment by ltongues** [comment]
Ok, thanks.
