### ISSUE TITLE
Document jQuery.htmlPrefilter

### ISSUE THREAD

**Issue by gibson042** [jquery/api.jquery.com#727]
Ref jquery/jquery#2203

**Comment by timmywil** [comment]
In this new page, let's include an example that addresses [this issue](https://github.com/jquery/jquery/issues/2668), in regards to leaving html within string contents alone.

**Comment by timmywil** [comment]
Also, see the original PR that we rejected because the edge case wasn't worth the size: https://github.com/jquery/jquery/pull/1374.

**Comment by AurelioDeRosa** [comment]
@gibson042 Did you have the time to take a look at this issue?
