### ISSUE TITLE
jQuery.unique: rename to jQuery.uniqueSort and deprecate jQuery.unique

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#731]
jQuery.unique will be [renamed](https://github.com/jquery/jquery/issues/2228) to make it clear that it sorts as well. This is only a deprecation notice. It will not be removed until 4.0.

**Comment by arthurvr** [comment]
PR: #736. Would be awesome if you could review, @timmywil.

**Comment by arthurvr** [comment]
Fixed in the v3 branch so closing this.

**Comment by timmywil** [comment]
Will be added in 1.12/2.2. 2c3a071abe236bf5815698556a5daf0e98692366
