### ISSUE TITLE
Ajax: preventing xss on untrusted URLs

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#732]
Per https://github.com/jquery/jquery/issues/2175, I recommend we add a note on the ajax page about retrieving scripts from an untrusted domain. Automatic JS execution and JSONP type inference can be prevented with options. All that is required is to set the dataType...

```js
$.get({
  url: "//untrusted.com/script.js",
  dataType: "text"
});
```

http://jsbin.com/rafima/1/edit?js,console

**Comment by AurelioDeRosa** [comment]
@dmethvin I think this issue has been addressed with https://github.com/AurelioDeRosa/api.jquery.com/commit/75d59a317552b4978bbd27ee50dad8bb27a5cb15. Would you agree?

**Comment by dmethvin** [comment]
Yep, thanks!
