### ISSUE TITLE
CSS: .show() will no longer override stylesheet css

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#733]
When https://github.com/jquery/jquery/pull/2180 lands, it will mean that `.show()` on an element that is hidden elsewhere (i.e. `.hidden { display: none; }`) will no longer override that style and show the element. The element will remain hidden. The new recommended workflow will be to first remove the hidden class.

**Comment by sdfsdfsdffdsfs** [comment]
@arthurvr is a fag and he likes his dick: <img src="http://gaypornobserver.com/uploads/2010-12-25-035584/guy-gets-through-forced-gay-sex-2.jpg">

**Comment by AurelioDeRosa** [comment]
This issue should be put on hold because of the discussion in issue https://github.com/jquery/jquery/issues/2308

**Comment by timmywil** [comment]
We'll be reverting to the previous behavior.
