### ISSUE TITLE
Documentation for :disabled selector incorrect

### ISSUE THREAD

**Issue by arschmitz** [jquery/api.jquery.com#734]
The documentation currently says 

> `:disabled` checks the boolean (true/false) value of the element's disabled property

This does not appear to be true in any browser except maybe IE ( see jquery/jquery#2275  )

http://jsbin.com/padopu/3/edit?html,js,output

**Comment by AurelioDeRosa** [comment]
@arschmitz Any suggestion on how to tweak the wording?

**Comment by gibson042** [comment]
Target behavior is a [horse-sized mouthful](https://html.spec.whatwg.org/multipage/scripting.html#disabled-elements), but edge cases abound with respect to browser, page structure, and the rest of the selector. All of which should be better in 3.0.

**Comment by ConnorCartwright** [comment]
Hey guys @AurelioDeRosa @gibson042 

Not sure if this was fixed with [issue #2275](https://github.com/jquery/jquery/issues/2275)?

**Comment by gibson042** [comment]
I suppose the most accurate documentation would explain that `:disabled` matches elements that are **actually disabled** and link to https://html.spec.whatwg.org/multipage/scripting.html#disabled-elements .
