### ISSUE TITLE
Document $.ready in 2.x and 1.x

### ISSUE THREAD

**Issue by benjamingr** [jquery/api.jquery.com#739]
Hey, first of all let me thank you for the move in 3.0 to promises, it will be awesome!

it would be really useful to document $.ready in 2.x and 1.x too, it seems like it's unlikely to change and it's very useful to use.

**Comment by dmethvin** [comment]
There was already conversation on this in #205 so I'll close this as a dup.

**Comment by arthurvr** [comment]
> so I'll close this as a dup.

**Comment by benjamingr** [comment]
@dmethvin you guys are odd.

I asked about this from an API perspective (vs docs) and I was told to move it here (to the docs) where it gets closed for being a dupe :P Fair enough I guess, I'll comment there.

**Comment by dmethvin** [comment]
No, #205 is a docs ticket, I just referenced the comment in the code repo. Sorry for the confusion but you were in the right place this time.

**Comment by mzgol** [comment]
@benjamingr Sorry, I didn't notice it was a duplicate.
