### ISSUE TITLE
iPhone 6 : jQuery(window).height() and .width() dont work - fix included..

### ISSUE THREAD

**Issue by seductiveapps** [jquery/api.jquery.com#741]
https://forum.jquery.com/topic/iphone-6-jquery-window-height-width-dont-work-one-bit-fix-included

Was testing my seductiveapps.com software on iPhone 6 recently and found that my dialog resizing routines worked but not the background resizing which uses jQuery(window).width() and .height()..
Well, it worked, but only after changing orientation on the damn thing once or twice..

This works from the start of the page's lifetime (not mine, found it a few years ago somewhere as browser-independent window width/height detection code) : var height = (window.innerHeight?window.innerHeight:document.documentElement&&document.documentElement.clientHeight?document.documentElement.clientHeight:document.body.clientHeight);

my jQuery version is 2.1.1

**Comment by seductiveapps** [comment]
oh, btw, that fix for iphone6 also works on:
- chrome for windows 8
- chrome for android 4.2 and 4.4 (can't test 5.x) + the regular browser on those android versions.
- chrome on ubuntu
- firefox on windows 7+ and ubuntu-since-2012-at-least
- internet explorer since windows 7 or even vista
- ipad air 2 and ipad 3 (dunno about earlier versions, can't test that)

**Comment by robertmaxrees** [comment]
This isn't the right place for bugs with the library itself - you want https://github.com/jquery/jquery/issues for that.

It looks like this bug may have already been submitted here:
https://github.com/jquery/jquery/issues/1729

**Comment by seductiveapps** [comment]
thx Robert. hope i've finally reached the devs' lair ;)

**Comment by arthurvr** [comment]
What @robertmaxrees said :)

**Comment by seductiveapps** [comment]
"i see a huuuuge somebody-elses-problem-field here", right? :p
