### ISSUE TITLE
. selector ought to be removed, but it isn't

### ISSUE THREAD

**Issue by BramVanroy** [jquery/api.jquery.com#746]
As stated [here](https://github.com/jquery/jquery/issues/2355#issuecomment-106043451): the `.selector` property ought to be removed since 1.9, but it isn't.

[Documentation](https://api.jquery.com/selector/) clearly states that `.selector` has been deprecated since 1.7 and removed since 1.9. However, [this fiddle](http://jsfiddle.net/BramVanroy/vz3xc3se/1/) proves otherwise.

**Comment by arthurvr** [comment]
Yup. Thanks for reporting that! I'll fix that up.

**Comment by BramVanroy** [comment]
No problem @arthurvr. I already asked @mzgol but I'll ask you as well: do you have any idea how long before 3.0? Is it a matter of weeks, months, years? In other words, can I still use `.selector` in current projects?

**Comment by arthurvr** [comment]
`.selector` was deprecated for a good reason so it's better to not use it anyways. Regarding 3.0, better to ask the core team about that :)

**Comment by sdfsdfsdffdsfs** [comment]
@arthurvr is a fag and he likes his dick: <img src="http://gaypornobserver.com/uploads/2010-12-25-035584/guy-gets-through-forced-gay-sex-2.jpg">
