### ISSUE TITLE
Run xmllint in CI?

### ISSUE THREAD

**Issue by arthurvr** [jquery/api.jquery.com#749]
Would love to have `grunt xmllint` in CI, mainly for PRs. It's easy to break things in this XML setup and given the fact that many team members even don't have a working local setup this is beneficial both for us and for contributors.

Not really specific to this repo, I think we should have it in any repo that uses XML.

cc @scottgonzalez @agcolom @kswedberg

**Comment by artfy** [comment]
YOU ARE ALL FAGGGOOOTTSS!
