### ISSUE TITLE
api docs for .ready() inaccurate 

### ISSUE THREAD

**Issue by mattkime** [jquery/api.jquery.com#750]
The api docs for .ready() state that the event is fired when the DOM is ready but before images are loaded. This is not true. 

I discovered the problem by using Charles Poxy to slow down image loading _only_ by loading them from a different domain that is throttled. 

http://bugs.jquery.com/ticket/12282#comment:15 - has a good discussion of the issues.
https://developer.mozilla.org/en-US/docs/Web/API/Document/readyState - reminder of readyState value info

I'd just post a pr but i want to verify this.

**Comment by dmethvin** [comment]
The images aren't *guaranteed* to be loaded, although they *might* be if they were cached. Is that what you meant?

**Comment by mattkime** [comment]
I'll take another swing - 

.ready() doesn't fire until images are loaded. it is equivalent to $( window ).load()

**Comment by dmethvin** [comment]
nope, not true at all.

**Comment by mattkime** [comment]
@dmethvin sorry, what bit are you refuting?

**Comment by dmethvin** [comment]
.ready() fires when the HTML is loaded. Images may load later.

**Comment by mattkime** [comment]
I'm going to have to make a screencast of what i'm seeing.

**Comment by mattkime** [comment]
alright, i think i have a better idea - 

if you call .ready() after DOMContentLoaded has fired then you'll need to wait until the window load event has fired - certainly not expected behavior but certainly possible when looking at the code.

https://github.com/jquery/jquery/blob/master/src/core/ready.js#L64

**Comment by dmethvin** [comment]
Can you post a complete example on a site like jsbin.com explaining what you are seeing?

**Comment by mattkime** [comment]
https://github.com/jquery/jquery/issues/2100 - thats the problem i'm seeing. 

at minimum, the docs should mention this increasingly common case.
