### ISSUE TITLE
Search should prioritize function names

### ISSUE THREAD

**Issue by clarkwinkelmann** [jquery/api.jquery.com#757]
Since a moment now I cannot use the search function correctly. Most of the keywords I type give me back the full list of functions listed alphabetically.

For example `html`, `on`, `prop`. I expect the first result to be the function with the same name, but instead it looks like it does a full text search of the documentation and return the matches alphabetically. And of course, theses terms are likely to appear in every description !

Maybe the function name should be the main criteria for ordering the results ?

In the current state, the search is pretty useless for me. I have to use `CTRL+F` on the api home page to find what I'm really looking for.

**Comment by scottgonzalez** [comment]
See jquery/jquery-wp-content#359.
