### ISSUE TITLE
Nitpicking: document that second parameter for `data()` is optional

### ISSUE THREAD

**Issue by jhfrench** [jquery/api.jquery.com#759]
The pattern documentd for the [`data()`](https://api.jquery.com/data/) method is `.data( key, value )`. Because the second attribute is optional ( the forth example illustrates this: `$( "body" ).data( "foo" ); // 52`), the pattern *should* be `.data( key, [value] )`.

Alternately, remove that forth example in deference to the [`.data( key )`](https://api.jquery.com/data/#data2) section.

**Comment by kswedberg** [comment]
The `data()` method has 2 signatures on that page:
https://api.jquery.com/data/#data1 and https://api.jquery.com/data/#data2

The first _stores_ data and returns `jQuery`, so it requires either two arguments or a single plain object argument; the second returns the value of the data, so it requires either no arguments or a single string argument. 

We document all of the overloaded getter/setter methods with two separate signatures like that: see [val()](https://api.jquery.com/val/), [text()](https://api.jquery.com/text/), and [html()](https://api.jquery.com/html/) for other examples.
