### ISSUE TITLE
Missing documentation for .toggleClass( [state] )

### ISSUE THREAD

**Issue by rosenfeld** [jquery/api.jquery.com#781]
The documentation here is insufficient:

http://api.jquery.com/toggleclass/#toggleClass-state

Also, the current behavior does not seem consistent from what one might expect by looking at the other signatures:

https://jsfiddle.net/jdoedx2v/4/

It seems the behavior of toggleClass() and toggleClass(true) are the same. I'd expect toggleClass(true) to always restore the original classes from the first call the same way as toggleClass(false) would always remove all original classes. But maybe I'm missing something because there's no proper documentation and I couldn't understand the real intention here...

**Comment by arthurvr** [comment]
Thank you for bringing this up, @rosenfeld. I agree that the current description is really bad.

Ref https://github.com/jquery/jquery/issues/2491 - let's hope we'll just be able to add a deprecation note :)

**Comment by rosenfeld** [comment]
Great, I'm +1 for removing that signature. I don't think anyone is using that... Sorry for the delay but my daughter was born a few hours after I created this ticket :)

**Comment by arthurvr** [comment]
> Sorry for the delay but my daughter was born a few hours after I created this ticket :)

Awesome! Congrats! :tada:

**Comment by rosenfeld** [comment]
Thanks :)

**Comment by timmywil** [comment]
The core team is in favor of removing this signature.

**Comment by AurelioDeRosa** [comment]
What's the action on this one? Should we just add a deprecation note for jQuery 3 or the doc should be improved anyway?

**Comment by dmethvin** [comment]
Well TBH I agree with @rosenfeld that the current behavior is completely non-intuitive, and we didn't exactly say what it did in the first place. So can we just drop the signature from the docs?

**Comment by arthurvr** [comment]
:+1: SGTM. If anyone likes that I'll take care of it.

**Comment by AurelioDeRosa** [comment]
I'm always for documenting methods, even if they were underused.

**Comment by dmethvin** [comment]
When you look at what the current methods do with Boolean tho, it's hard to imagine anyone found them useful or correct.

**Comment by AurelioDeRosa** [comment]
Should we close this issue because of https://github.com/jquery/jquery/pull/2618?

**Comment by dmethvin** [comment]
Yes, I think this should be closed with no action, since we are removing it in 3.0 and it was pretty strange before that. Objections?

**Comment by AurelioDeRosa** [comment]
I think we have documented the bare minimum in case someone was using it (hopefully nobody). No other actions are needed IMO. I'm going to close this one and open an issue for branch `v3.0.0-docs` to document that the signature has been removed.

**Comment by mgol** [comment]
@AurelioDeRosa Did you open an issue against the `v3.0.0-docs` branch in the end? We have to be sure it's not documented to work in jQuery 3.0.

**Comment by mgol** [comment]
Ah, sorry, I forgot https://github.com/jquery/jquery/commit/a4d16a26abe3ea36337f7bfc4d1bfe13b893cd17. And the issue about deprecation is #851.
