### ISSUE TITLE
.val() doesn't fire change Event

### ISSUE THREAD

**Issue by toxcct** [jquery/api.jquery.com#79]
Hello,

I just noticed that using .val() on a form field (text field) doesn't execute the "OnChange" event handler binded on that Field...

Also, the .val() documantation page ( http://api.jquery.com/val/ ) doesn't mention anything about this, so I suspect this to be a bug.

Can you tell if this is a desired behavior or not ?
Must I say that I'm using jQuery 1.8.2.

Thanks.
Toxcct

**Comment by victor-homyakov** [comment]
Taking into account amount of similar [StackOverflow questions](http://stackoverflow.com/search?q=jquery+val+trigger+change), it still may have sense to clarify this subtle point in jQuery documentation.

**Comment by dmethvin** [comment]
Sure, pull requests are welcome at https://github.com/jquery/api.jquery.com .
