### ISSUE TITLE
ajax response cannot been parsed correctly in iOS chrome browser

### ISSUE THREAD

**Issue by wucxzx** [jquery/api.jquery.com#795]
I am developing a web application which use ajax request to retrieve data from server side application. The function working fine in all desktop browsers and most mobile browser except iPhone chrome. 

The ajax request was sent correctly but the data returned from server was empty in ajax success callback function.

**Comment by AurelioDeRosa** [comment]
This is not a documentation issue, but a code one. Please, report it to the [jQuery repository](https://github.com/jquery/jquery). I'm closing this issue.
