### ISSUE TITLE
`One` docs misleading

### ISSUE THREAD

**Issue by benjamingr** [jquery/api.jquery.com#796]
The example for `.one` somewhat implies that `one` disables other event listeners added for the same event which is not the case.

Clarifying it could be nice.

**Comment by AurelioDeRosa** [comment]
Hi @benjamingr. Can you clarify which example you are referring to and what kind of additional explanation you'd like us to add?

**Comment by benjamingr** [comment]
I have a friend who started learning jQuery. He understood `one` as "it executes the event and removes all other event handlers for the event" rather than "it executes the event handler and removes it from the event" (which is what I told him it does and he refused to believe until I showed him in code).

I think the docs could be a little clearer on what it does :)

**Comment by AurelioDeRosa** [comment]
@benjamingr are you interested in submitting a PR for this issue? We love contributions.

**Comment by benjamingr** [comment]
I've talked to the friend and he agreed to work on a PR. I'll ask him to comment here about what caused the confusion and walk him through the process (I've been somewhat involved in jQuery before, but not the docs yet :)).
