### ISSUE TITLE
Clarify `always` callback for animations

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#803]
The docs are unclear that `always` is also a per-element callback, like `complete`.

https://github.com/jquery/jquery/issues/2585#issuecomment-138949538

**Comment by AurelioDeRosa** [comment]
The PR looks good to me and can be merged.

I agree that we should create a global note that is included in all the files affected. I suggest to merge this PR and then open a new issue that takes into account the general problem.
