### ISSUE TITLE
Document change in addClass/removeClass for jQuery 3

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#814]
jQuery 3 [changes the behavior of addClass/removeClass](https://github.com/jquery/jquery/issues/2199) for better SVG support. Thanks you @gibson042 for [the feedback](https://github.com/jquery/api.jquery.com/pull/813#discussion_r41413528).

**Comment by dmethvin** [comment]
Something like this paragraph might work:

In HTML documents *only*, browsers keep the `class` attribute (e.g. `$(elem).attr("class")` or `elem.getAttribute("class")` and the `className` property (e.g. $(elem).prop("className") or `elem.className`) in sync; when you change one of them the browser updates the other. Prior to jQuery 3.0, jQuery used the `className` property in `addClass` and `removeClass`, which is not compatible with XML or SVG documents. As of jQuery 3.0, the `class` attribute is used instead and these methods can be used on XML or SVG.

**Comment by AurelioDeRosa** [comment]
Fixed with commit 4651f4415ca00b8f9862d3a39a3eeea8600ddfff.

**Comment by timmywil** [comment]
Will be added in 1.12/2.2. 9bf0ad3c1e3816da7ebb331b3fda1e04df5287f6

**Comment by AurelioDeRosa** [comment]
Thank you for that @timmywil. Should I include it in the main branch once we release 1.12/2.2?

**Comment by timmywil** [comment]
Yup, I'm trying to get the branch to point where it can be merged on release.
