### ISSUE TITLE
Feature Request: ajaxError interceptor rather than on document

### ISSUE THREAD

**Issue by flavouski** [jquery/api.jquery.com#815]
I call the .ajaxError() command on the document object, but it doesn't do enough for our situation.

```$(document).ajaxError(function(event, jqxhr, settings, thrownError) {}```

It isn't intercepting the ajax request, it is waiting for it to bubble-up to the document, which I can see a case for both.  But currently there is no way to intercept it (unless making your own ajax method which calls JQuery's, but even then, 3rd party plugins aren't able to be controlled easily).

I guess this is a feature, but it would be nice to have it mentioned in the documentation also.

**Comment by AurelioDeRosa** [comment]
Hi.

The `ajaxError()` method should only be attached to `document` since version 1.8. If you want to do something before an Ajax request is sent, you might want to use [`.ajaxPrefilter()`](http://api.jquery.com/jQuery.ajaxPrefilter/).

**Comment by flavouski** [comment]
Ohhh, I didn't see it listed in http://api.jquery.com/category/ajax/global-ajax-event-handlers/ and just assumed that there wasn't any other options...
Thanks!

**Comment by flavouski** [comment]
Just wanted to add here is the code that worked for me is below.  It still uses the errors added to via original promises to ajax requests.

```$.ajaxPrefilter(function( options, originalOptions, jqXHR ) {
	var error = options.error;
	options.error = function (jqXHR, textStatus, errorThrown) {
		if (jqXHR.status == 401 || jqXHR.status == 403) { 
			//do stuff
		}
	}; 
```
