### ISSUE TITLE
isNumeric(): currently inadequate/inaccurate

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#817]
Ref https://github.com/jquery/jquery/issues/2662

`isNumeric()` does not only determine whether a given argument is a number. It also checks to see if string input can be coerced into finite numbers. Anything that is not a number or string will return false.

**Comment by AurelioDeRosa** [comment]
Closed via 4e65b6dfa6c6f2d486572c30dbf5c436b1524030
