### ISSUE TITLE
Note that `event.which` is deprecated and itself uses deprecated properties

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#821]
See https://github.com/jquery/jquery/issues/2667

**Comment by AurelioDeRosa** [comment]
Should be set this as deprecated now considering the **very low** support of the new standard?

**Comment by dmethvin** [comment]
Here is the caniuse.com info for [KeyboardEvent](http://caniuse.com/#search=KeyboardEvent) and it looks like the deprecated `keyCode` still wins by a mile, so you may be right.

**Comment by mgol** [comment]
We've decided to not mark this API as deprecated in the end as there's no direct native replacement. See https://github.com/jquery/jquery/issues/4755#issuecomment-664501730.
