### ISSUE TITLE
toggle event is deprecated, but no replacement provided

### ISSUE THREAD

**Issue by IanKemp** [jquery/api.jquery.com#825]
https://api.jquery.com/toggle-event/

The documentation mentions that the `toggle` **method** has been deprecated in 1.8 and removed in 1.9, but doesn't explicitly mention if the **event** itself is still supported (via `.on("toggle")`) - it appears not to be.  

If the event is no longer supported, it would be useful to add a message explaining this, and potentially an example for how to emulate this event's behaviour.  

If it is, an example to demonstrate `.on("toggle")` would be helpful.

**Comment by dmethvin** [comment]
From the docs:

> Note: This method signature was deprecated in jQuery 1.8 and removed in jQuery 1.9.

> The `.toggle()` method binds a handler for the `click` event,

There is no standards-defined `toggle` event, although someone could certainly define one. This documentation doesn't mention one at all and explicitly says it deals with the `click` event. Other than being the same word "toggle" there isn't a connection.
