### ISSUE TITLE
toggle() method's name violates Principle of Least Astonishment

### ISSUE THREAD

**Issue by IanKemp** [jquery/api.jquery.com#826]
https://api.jquery.com/toggle/  

The `toggle()` method's name does not sufficiently explain its purpose. *What* does it toggle - display, visibility, element state, ...?  

This method should be renamed to something more intuitive. I am aware that naming things is one of the unsolved problems of programming, but perhaps some variation of `toggleDisplay()` would be suitable.

**Comment by dmethvin** [comment]
The docs *do* explain it though, that's what the docs are for?

> The matched elements will be revealed or hidden immediately, with no animation, by changing the CSS display property. If the element is initially displayed, it will be hidden; if hidden, it will be shown. The display property is saved and restored as needed. If an element has a display value of inline, then is hidden and shown, it will once again be displayed inline.

Since the method has been around for a decade now, renaming it will just cause more confusion. We specifically deprecated the lesser-used toggle-event method to make it clear that this API does one thing.

**Comment by timmywil** [comment]
Agreed. It's also easy to add your own aliases:

```js
jQuery.fn.toggleDisplay = jQuery.fn.toggle;
```
