### ISSUE TITLE
Attr: selectMultipleWithNoValue.val() now returns [] instead of null

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#828]
From https://github.com/jquery/jquery/issues/2562

We have this line...

> In the case of select elements, it returns null when no option is selected and an array containing the value of each selected option when there is at least one and it is possible to select more because the multiple attribute is present.

which could say something like this instead...

> When called on select elements that have no option selected, the `.val()` method returns `null`, or an empty array if the multiple attribute is present. If at least one option is selected, either the value or an array of values will be returned.

Also, one of the examples will need editing.

Where we have...

```js
var multipleValues = $( "#multiple" ).val() || [];
```
we can shorten it to...
```js
var multipleValues = $( "#multiple" ).val();
```

**Comment by dmethvin** [comment]
Although you'd need to keep the old code if you're using an older version of jQuery, so we'll probably need a version note here?

**Comment by timmywil** [comment]
True. I'm not sure how to incorporate the version differences in a concise manner. Maybe we need @kswedberg's English powers.

**Comment by AurelioDeRosa** [comment]
@kswedberg Can you please take a look at this issue?

**Comment by kswedberg** [comment]
Sure. Which version(s) introduced the change in return value?

**Comment by mgol** [comment]
> Sure. Which version(s) introduced the change in return value?

Version 3.0.

**Comment by kswedberg** [comment]
ah, ok. I'll put something together later today.

**Comment by kswedberg** [comment]
errrr. tomorrow. sorry.
