### ISSUE TITLE
Document jQuery.speed

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#830]
https://github.com/jquery/jquery/pull/2713 Brought up the issue that `jQuery.speed` is exposed and undocumented. Since jQuery UI uses it, we've decided to document it.

**Comment by AurelioDeRosa** [comment]
I think I need a bit of guidance here. From the source I get the followings:

- This method works with animations (specifically with `animate()`)
- It accepts three arguments, all of which are optional
- The method returns an object literal containing a set of properties whose value are the combination of the provided arguments and some defaults (e.g. `400` for speed)

Now, what's the use case for such method from a user point of view? Any hint on an example we should include in the documentation page?

**Comment by scottgonzalez** [comment]
Everything you've gathered so far is correct. The use case is plugin developers who are creating new animation methods. For example, the animated form of `.addClass()` that exists in jQuery UI. Letting `$.speed()` do all the parameter hockey and normalization for you, rather than duplicating the logic yourself, makes these implementations much saner.

**Comment by scottgonzalez** [comment]
I'm not sure if there's a reasonably sized example that can be included in the docs, but the audience is so small and anyone that wants to use this will know how they want to use it without an example so I think it's fine to just explain what it does and leave it at that.

**Comment by AurelioDeRosa** [comment]
Thank  you for the explanation @scottgonzalez, especially for the use case. It makes a lot of sense now. I'll submit a PR by tomorrow.

**Comment by AurelioDeRosa** [comment]
I tried my best to document this method. Please, review when you get a moment.
