### ISSUE TITLE
Second argument of globalEval method

### ISSUE THREAD

**Issue by markelog** [jquery/api.jquery.com#831]
In 3.0, `globalEval` will have a second argument, see - https://github.com/jquery/jquery/commit/22449eb968622c2e14d6c8d8de2cf1e1ba4adccd

I'm not sure if should document it or not. 

I wouldn't... and declared is as "internal", i think migrate might want consider adding a check for it too.

I wouldn't since it was removed from the real `window.eval` and was never standartized, and since this function is called as `globalEval`, so i would add a comment to the `jQuery.globalEval` instead.

/cc @dmethvin, @mzgol, @timmywil

**Comment by mzgol** [comment]
I've filed multiple issues & commited many changes that removed exposure of internal parameters from various methods and I wouldn't want us to go in the opposite direction. If we want this parameter as internal we should declare a `globalEval` function in a closure and expose only a function that accepts one parameter, similarly what I did in 04a29696e5b176ac66401120e433d52425222f0f. Otherwise, it should be documented.

cc @timmywil

**Comment by timmywil** [comment]
I'm fine with documenting it. It could be useful to pass the context, and required in some cases. `globalEval` is different than `eval` in that we are changing the context in which the code is executed. The ability to pass the desired context makes sense to me.

**Comment by mzgol** [comment]
If we wanted this parameter to not just be internal, we should have proper tests for `jQuery.globalEval( code, context )` which we currently lack.

**Comment by mzgol** [comment]
@timmywil 

> globalEval is different than eval in that we are changing the context in which the code is executed. The ability to pass the desired context makes sense to me.

:+1: But we need to write tests for it.

**Comment by markelog** [comment]
Well, @mzgol, you called "LGTM" on this change - https://github.com/jquery/jquery/pull/2696

I really think we should be more careful, not sporadic, changing signatures like that. That `context` argument, i think this would need to be outlined next time.

I'm big -1 on this, method called `jQuery.globalEval`, the name says in what context it should be executed. Also, JS version of `eval` **now** has luck of argument like that.

So for my taste, documenting it as public, is confusing, contradictory and not compatible with spec

**Comment by mzgol** [comment]
> Well, @mzgol, you called "LGTM" on this change - jquery/jquery#2696

Everyone makes mistakes. :-)

I'm +0 about making it official. I can see it may be useful, I also understand @markelog's concerns. I just want us to do one of the following two things - either document & test it or to remove the second parameter and move it to an internal function. Exposing it & not documenting is a bad idea IMO.

**Comment by timmywil** [comment]
@markelog `globalEval` is not the same as native `eval`. There's no spec to align with here. Even with providing a context, that context must be a document, which means its name is still accurate. It's still executing globally, but globally in the right window (like in an iframe).

**Comment by markelog** [comment]
@mzgol 

> remove the second parameter and move it to an internal function

Agreed on that one, private module which could called from `globalEval` and `manipulation` module.

> globalEval is not the same as native eval

`globalEval` is the same as calling native indirectly. You are right though in the sense that this is not a "shim" and it as our API. But just like we trying to be close to the DOM spec with `events` logic. I think we should apply same efforts here too.

> It's still executing globally, but globally in the right window (like in an iframe).

Yeah, that what i call "confusing". It has a `context` argument, but it couldn't be a function, it could be only `document` node? Not even a window? Using here document node is a clear side-effect to me.

Besides, there isn't any real use-case asked by the users.

**Comment by timmywil** [comment]
> Besides, there isn't any real use-case asked by the users.

Well, that's a fair point. We need it to fix a bug in manipulation, but you're right that we didn't get a request to deal with this in `globalEval` directly. If we privatize it, we may as well put `globalEval` in its own file and remove the argument from the exposed parameter list.

**Comment by mzgol** [comment]
@markelog 
> Yeah, that what i call "confusing". It has a `context` argument, but it couldn't be a function, it could be only `document` node? Not even a window? Using here document node is a clear side-effect to me.

We have an API with similar behavior ATM: http://api.jquery.com/jQuery/#jQuery2.

**Comment by markelog** [comment]
>  If we privatize it, we may as well put globalEval in its own file and remove the argument from the exposed parameter list.

Yeah, that is my suggestion. 

> We have an API with similar behavior ATM: http://api.jquery.com/jQuery/#jQuery2.

I see the resemblance, but i wouldn't call it "similar".

**Comment by dmethvin** [comment]
I'd say let's just document the arg. It's not something most people will need to know about and it's subject to restrictions, but it seems like a lot of work to try and hide the arg. Taking the whole method private might cause some pain, it was [described in some detail](http://perfectionkills.com/global-eval-what-are-the-options/) by kangax a few years back so people know about it that way, even if our own docs are somewhat lacking.

**Comment by markelog** [comment]
It could be harder to support and maintain documentation, tests and logic for such controversal argument that is probably needless and we could put ourself in tough predicament if we would need to switch implementation to indirect/something-different.

Not sure if i see the issue with hiding it, we did so many times and didn't had any problems with such approach, like `on` - https://github.com/jquery/jquery/blob/78b9eac1198627eb4dad0cc35334c7704449f310/src/event.js#L33 and https://github.com/jquery/jquery/blob/78b9eac1198627eb4dad0cc35334c7704449f310/src/event.js#L658

It could be done pretty much the same way. Only moved to different module.

**Comment by timmywil** [comment]
> Taking the whole method private might cause some pain

Just to be clear, I wasn't suggesting we make `globalEval` private, just the argument.

The main question is whether or not the argument is useful to users. If we think it is, we may as well document it. If not, make it private. We can handle maintenance questions after that question is answered.

**Comment by markelog** [comment]
Anyways, this is how i see it - https://github.com/jquery/jquery/pull/2718. I wouldn't envy the person, who would need to answer questions like and then tediously document incorrect input -  

```js
jQuery.globalEval("alert(1)", document.implementation.createHTMLDocument( "" )); // ?!
jQuery.globalEval("alert(1)", document.createDocumentFragment()); // ?!
jQuery.globalEval("alert(1)", document.body.createShadowRoot()); // ?!
```

Or try this thing to work

**Comment by markelog** [comment]
On the meeting, it was decided to not expose the second argument
