### ISSUE TITLE
noConflict - second example need call moved

### ISSUE THREAD

**Issue by drummike** [jquery/api.jquery.com#835]
In the second code snippet shown on the noConflict page there are these lines:
<snip>
$.noConflict();
jQuery( document ).ready(function( $ ) {
  // Code that uses jQuery's $ can follow here.
});
// Code that uses other library's $ can follow here.
</snip>
The noConflict call should be moved down, so it happens after the line with ready(function($) 
Otherwise $ is undefined, or defined as belonging to some other library.

I made a fork with the change to entries/jQuery.noConflict.xml

**Comment by mzgol** [comment]
No, this example is correct. `$.noConflict()` restores the previous global value of `$` but not `jQuery`. The .ready function gets a parameter that's assigned to the jQuery instance so `$` inside of the ready callback is equal to the first jQuery. This is a function parameter and not the global `$`.

**Comment by drummike** [comment]
Are you certain? The reason I ask is that I tried that code and it gave me an error.

<!DOCTYPE html>
<html lang="en">
<body>
<script src="../js/jquery.js"></script>
<script>
$.noConflict();
jQuery( document ).ready(function( $ ) {
  // Code that uses jQuery's $ can follow here.
  $.alert("that dog don't hunt");  // line 9 - for reference
});
// Code that uses other library's $ can follow here.

</script>
</body>
</html>
== console output
Uncaught TypeError: $.alert is not a function

**Comment by scottgonzalez** [comment]
Well, `$.alert` is not a function that *should* exist given that code, since there is no such method in jQuery.

**Comment by drummike** [comment]
Duh! Oh well, a PBCAK.

Cheers.
