### ISSUE TITLE
Minor tweak: note that :hidden is identical to not(:visible) and vice-versa

### ISSUE THREAD

**Issue by mcdurdin** [jquery/api.jquery.com#838]
Given the documentation for the two selectors https://api.jquery.com/hidden-selector/ and https://api.jquery.com/visible-selector/ have different nuances, it would be helpful to note that the implementation of :hidden simply returns not(:visible):

    jQuery.expr.filters.hidden = function( elem ) {
    	return !jQuery.expr.filters.visible( elem );
    };

Better yet would be to make the notes from each page consistent.

See also http://stackoverflow.com/questions/17425543/difference-between-hidden-and-notvisible-in-jquery

**Comment by AurelioDeRosa** [comment]
I'm not sure the API page should document how we actually implement a method internally. This might change in the feature without affecting what the outcome is and how a user would call the API. Any thoughts?

**Comment by mcdurdin** [comment]
It's not so much about documenting the internal implementation as noting that one is the opposite of the other, and making the documentation of the two methods consistent. And vice-versa, if there are differences, then document why they differ.

**Comment by dmethvin** [comment]
I'd be fine with a reference such as "Also see the `:hidden` selector" in the entry for `:visible` and vice versa.

**Comment by AurelioDeRosa** [comment]
I've submitted a PR to address this issue.

**Comment by mcdurdin** [comment]
Yes, that's good.
