### ISSUE TITLE
Update references to jQuery 1.4 release

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#843]
The jQuery 1.4 release was a bit strange because the info was posted at jquery14.com rather than on the blog. We took that domain down a while back. 

Content can be found here:
https://web.archive.org/web/20120207190412/http://jquery14.com/day-01/jquery-14
https://web.archive.org/web/20120302231013/http://jquery14.com/day-12/jquery-141-released
- [ ] Update blog post at blog.jquery.com with the info from those pages
  - https://blog.jquery.com/2010/01/14/jquery-14-released/
- [ ] Change jquery14.com links that are still broken after #841, you can see the links to jquery14.com there that need to be changed.

**Comment by EhsanKia** [comment]
This should really be updated now. jquery14 seems to now be owned by some scam site, and two of your documentation page currently link to it.

**Comment by dmethvin** [comment]
@EhsanKia Can you point me direclty to those documentation pages? Sorry if they're referenced somewher here but since you said "two" I'm thinking you know which ones they are.

**Comment by EhsanKia** [comment]
@dmethvin There are two, 1.4 and1.41
https://api.jquery.com/category/version/1.4/
https://api.jquery.com/category/version/1.4.1/

**Comment by mgol** [comment]
There is also a blog post at https://blog.jquery.com/2010/01/14/jquery-14-released/

**Comment by mgol** [comment]
I fixed the API parts in c2f3d41 (forgot to link to the issue, oops). @dmethvin can you fix the blog post?

**Comment by mgol** [comment]
Ping @timmywil or @dmethvin :)

**Comment by dmethvin** [comment]
Done!
