### ISSUE TITLE
jQuery.extend with deep=true causes unpredicted side effects

### ISSUE THREAD

**Issue by maciej-pawlisz** [jquery/api.jquery.com#847]
There is a problem with deep extending - nested objects get overritten, which might be very confusing:
```javascript
var nested={x:1}
var obj={n:nested}
$.extend(true,obj,{n:{x:2,y:2}}) 
console.log(nested)
{x:2, y:2, } 
```
It is even worse, when `nested` will be a prototype - we can get very unexpected errors (I experienced it when using jquery.rest and I changed `verbs`)

In `jQuery.extend` function there is a comment, which suggests that this situation should be avoided :
```javascript
         // Never move original objects, clone them
        target[ name ] = jQuery.extend( deep, clone, copy );
```
but it is not working as the comment suggests. Maybe it should be replaced with:
```javascript
        target[ name ] = jQuery.extend( deep,{}, clone, copy );
```

**Comment by AurelioDeRosa** [comment]
This sounds like a bug in the jQuery library, not the documentation. Can you please report it there ([https://github.com/jquery/jquery/issues](https://github.com/jquery/jquery/issues))? Also, I think they are going to ask you to provide a demo (JSBin, JSFiddle, CodePen, and so on).
