### ISSUE TITLE
Document that .toggleClass( boolean ) has been deprecated in jQuery 3

### ISSUE THREAD

**Issue by AurelioDeRosa** [jquery/api.jquery.com#851]
Reference: https://github.com/jquery/jquery/pull/2618.

**Comment by dmethvin** [comment]
Given that is wasn't really documented before (just a signature with no real explanation) I wonder if we should relegate this to the release notes.

**Comment by timmywil** [comment]
We've decided to save this removal for 4.0. We just need to mark it deprecated in 3.0.

**Comment by dmethvin** [comment]
Oh I missed that I guess. Yes, it's still in master so deprecate in 3.0 and remove in 4.0 then.

**Comment by AurelioDeRosa** [comment]
No worries Dave.
