### ISSUE TITLE
Clarify and correct .closest() docs

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#857]
https://github.com/jquery/jquery/issues/2796

Remove reference to `this.context` ("context of the jQuery set") since it has been deprecated and was removed in 3.0.

Clarify that the `context` argument is used for jQuery-extension positional selectors such as `:first` and `nth()` but otherwise only for deciding how far up the tree to stop comparing nodes . That is, the context is not used as the root for matching the selector.

**Comment by gibson042** [comment]
> Clarify that the `context` argument is used for jQuery-extension positional selectors such as `:first` and `nth()` but otherwise only for deciding how far up the tree to stop comparing nodes . That is, the context is not used as the root for matching the selector.

I'd like to take a different tack and [ensure that positionals never match](https://github.com/jquery/jquery/pull/2818), in which case this issue is satisfied by removing the "If no context is passed in…" sentence.
