### ISSUE TITLE
CSS: refresh language about old IE

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#867]
`currentStyle` and `runtimeStyle` are only in old IE, but the docs just say "Internet Explorer." We probably want to specify that it only applies to IE<9.

See https://github.com/jquery/jquery/issues/2837

**Comment by mgol** [comment]
Should we even mention IE<9 here? We're dropping support for it so it doesn't make much sense to advertise what we used to do for it.

**Comment by dmethvin** [comment]
Once IE8 is really dead I can see dropping it, but it's useful info for people who still have to deal with it. Maybe in a year or two we make a run through the docs and remove all the IE apologies. :smiley_cat:
