### ISSUE TITLE
Add jQuery.escapeSelector

### ISSUE THREAD

**Issue by timmywil** [jquery/api.jquery.com#880]
See https://github.com/jquery/jquery/issues/1761

Document the new method `jQuery.escapeSelector`, for escaping strings for use in selectors. Much the same as the native [CSS.escape](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape), but replaces the null character with U+FFFD, rather than throwing an error.

**Comment by gibson042** [comment]
> Much the same as the native [CSS.escape](https://developer.mozilla.org/en-US/docs/Web/API/CSS/escape), but replaces the null character with U+FFFD, rather than throwing an error.

Actually, it's identical to `CSS.escape` as specified in [the current CSSOM draft](https://drafts.csswg.org/cssom/#the-css.escape()-method) (cf. https://drafts.csswg.org/cssom/#serialize-an-identifier ), which was updated when I raised the issue. :)

**Comment by timmywil** [comment]
What @gibson042 said. I misunderstood.

**Comment by timmywil** [comment]
So, I assume MDN needs an update.
