### ISSUE TITLE
.outerWidth() and .outerHeight() don't specify the default values of the 'includeMargin' argument

### ISSUE THREAD

**Issue by IanKemp** [jquery/api.jquery.com#882]
All other function docs specify the default value for their optional parameters (e.g. `.animate()`: `duration (default: 400)`) , but `.outerWidth()` and `.outerHeight()` do not. As far as I'm aware the default value is `includeMargin: false` but I'd appreciate if someone could double-check this.

**Comment by dmethvin** [comment]
The text of the description clarifies the default value but it seems like a good idea to give the default above in case someone doesn't read that far, or if the XML is being processed by an automated tool. Would you like to submit a pull request for this?
