### ISSUE TITLE
Warn about the lack of official SVG support for attribute manipulation (and maybe in other cases?)

### ISSUE THREAD

**Issue by mgol** [jquery/api.jquery.com#884]
In https://github.com/jquery/jquery/issues/2910 @agcolom noticed that our lower-casing logic for attribute names breaks SVG attribute handling. This doesn't matter for us as we don't support SVG manipulation (with rare exceptions like class manipulation) but it may confuse users as some APIs might work in most/some cases and only break with others. We might want to warn on a couple of cases that even if it works, it's unsupported.

**Comment by mgol** [comment]
While we're at support for SVG class manip, I've just created #885 to document that.

**Comment by timmywil** [comment]
If we're removing the lowercasing in 3.0, how hard would it be to support attribute manipulation on SVG elements?

**Comment by mgol** [comment]
I'd guess it should *just work*™, we'd just need to add some tests an make sure they do pass in all supported browsers.

**Comment by mgol** [comment]
@timmywil I have a PR for the removal: https://github.com/jquery/jquery/pull/2916. I can add some tests there and check if they pass.

**Comment by AurelioDeRosa** [comment]
Should I wait before submitting a PR to note that we don't really support SVG documents?

**Comment by timmywil** [comment]
@AurelioDeRosa Yea, I'd like to explore how easy it would be to support SVG in this area.

**Comment by mgol** [comment]
@AurelioDeRosa We've established we're not going to officially support SVG attribute manipulation. That said, [I've landed a change](https://github.com/jquery/jquery/commit/615d92517b52d7e70d1c83397ed8207373a95137) to jQuery that should make it work for most of the cases (basically removing our lowercasing logic).

It's still unsupported, though, so a note in the docs sounds like a good idea.

**Comment by dmethvin** [comment]
BTW the change @mgol mentions above lands in version 3.0. We couldn't take it out in 1.x because it's required for IE7 and we left it in 2.x for consistency.

**Comment by AurelioDeRosa** [comment]
What about something like:

> jQuery doesn't officially support SVG. Using jQuery methods on SVG documents, unless explicitly specified, might cause unexpected behaviors. Examples of methods that support SVG are `addClass` and `removeClass`.

Also, where do you think we should add this note?

**Comment by mgol** [comment]
The note seems good to me; as to where to put it - good question! General pages tend to be overlooked and we already mention lack of SVG support on the [wont-fix contribute page](https://contribute.jquery.org/wont-fix/#svg-vml-or-namespaced-elements-bugs); I was thinking about making it a template and include this template on a couple of high-profile APIs like `.attr`, `.removeAttr` or `.find`.

**Comment by AurelioDeRosa** [comment]
Thank you for the comment @mgol. Anyone else wants to comment on this? Since it's a change that will affect quite a few pages I'd like to hear from more people before submitting a PR.

**Comment by dmethvin** [comment]
Your text looks good although I would `s/specified/documented for that method/` to clarify that the method docs will say when they support SVG, otherwise assume they do not. Also that note should be clear that add/removeClass only support SVG as of 3.0.

**Comment by AurelioDeRosa** [comment]
Thank you @dmethvin. I'm going to submit a PR.
