### ISSUE TITLE
Document that SVG class manipulation is supported in jQuery 1.12, 2.2 or newer

### ISSUE THREAD

**Issue by mgol** [jquery/api.jquery.com#885]
jQuery doesn't generally support SVG but due to the fact we've received exceptionally many questions about class manipulation support and it was relatively cheap for us to do, we added such support in jQuery 1.12/2.2. We should document that `addClass`, `removeClass`, `hasClass` and `toggleClass` is now supported on SVG nodes and we have [unit tests for that](https://github.com/jquery/jquery/blob/3f46cec169addb096fe576313e5cc6dde8618c04/test/unit/attributes.js#L1538-L1564).

The note should also warn that class manip support is an exception and that most jQuery APIs don't support SVGs.

**Comment by AurelioDeRosa** [comment]
The `addClass` and `removeClass` have already [a note about SVG support](https://github.com/jquery/api.jquery.com/blob/674b7514dd46be08c75f8e38d60a90a724729159/entries/addClass.xml#L23). I'm going to add a note for `hasClass` and `toggleClass`.
