### ISSUE TITLE
jQuery.parseJSON will be deprecated in jQuery 3.0.0

### ISSUE THREAD

**Issue by mgol** [jquery/api.jquery.com#898]
`jQuery.parseJSON` will be deprecated in jQuery 3.0.0. `JSON.parse` should be used instead. This needs to be documented.

See https://github.com/jquery/jquery/issues/2800.

**Comment by AurelioDeRosa** [comment]
Issue closed via https://github.com/jquery/api.jquery.com/commit/d3b74ac4c6f5b28bc6535c814c145eb73aa910fb.
