### ISSUE TITLE
category not found

### ISSUE THREAD

**Issue by feiwen8772** [jquery/api.jquery.com#908]
http://api.jquery.com/category/version/1.12/2.2/ this page not found。

/version/1.12&2.2/ maybe suitable。

**Comment by AurelioDeRosa** [comment]
This issue can be found at [$.uniqueSort()](https://api.jquery.com/jQuery.uniqueSort/). It was introduced in [commit 82c1f4c](https://github.com/jquery/api.jquery.com/commit/82c1f4c57d31142a4851d50cad4a0233a8c27036). @timmywil do you have any suggestion on the action here?

**Comment by timmywil** [comment]
1.12&2.2 works for me.

**Comment by AurelioDeRosa** [comment]
Is our system able to deal with the `&` character? If not, we could use a dash.

**Comment by dmethvin** [comment]
Dash sounds safest.

**Comment by timmywil** [comment]
Dash makes it look like 1.12 to 2.2, tho.

**Comment by dmethvin** [comment]
True. If `&` or `&amp;` works I'm down with it but I always get a bad feeling about character entities.

**Comment by kswedberg** [comment]
@timmywil , @AurelioDeRosa : When I add the `1.12&amp;2.2` slug to categories.xml, I get `Warning: Invalid slug: 1.12&2.2.`

**Comment by AurelioDeRosa** [comment]
So, I had a bit of time to dig into this issue. The `&` doesn't work and the dash is the only character I managed to have working. Is everyone happy with it?

**Comment by dmethvin** [comment]
Dash works for me. You could say my hopes were dashed. Or not.

**Comment by kswedberg** [comment]
@AurelioDeRosa Works for me!

**Comment by mgol** [comment]
@kswedberg You need to add a new tag (`npm version patch` & push) to have the changes reflected on the site.

**Comment by kswedberg** [comment]
@mgol right you are! Sorry, dropped the ball there.

**Comment by kswedberg** [comment]
Hmm. seems you already did it. Thanks, @mgol !

**Comment by mgol** [comment]
Yup, I just wanted to remind you about it for the sake of the future. :)

-- 
Michał Gołębiowski
