### ISSUE TITLE
Document jQuery.easing with one argument

### ISSUE THREAD

**Issue by markelog** [jquery/api.jquery.com#912]
We tried to remove additional arguments it in 3.0, turns out there is a lot of plugins using them, so we decided to deprecate it first before removing in some next major, but we can't deprecate something internal, so we decided to just document it as one argument method.

**Comment by dmethvin** [comment]
In particular the [jQuery Easing](https://github.com/gdsmith/jquery.easing) plugin which is in use by about [8 percent of the top million sites](http://trends.builtwith.com/javascript/jQuery-Easing). The impact is probably more when you realize the code is small and may have been copy/pastaed to other places as well.

**Comment by scottgonzalez** [comment]
It's entirely possible that those stats are completely wrong too. You'd have to know how BuiltWith is detecting the easing plugin and whether that logic can differentiate between jQuery Easing and jQuery UI.

**Comment by kswedberg** [comment]
Presumably, though, if BuiltWith were including jQuery UI in its results for jQuery Easing, it would claim more than **18** percent, which is what BuiltWith says jQuery UI has out of the top 1 million. Even if only half of jQuery UI installs included UI effects core, that would still put easing over 9%. So, I'm guessing they have some way of differentiating the two.

**Comment by dmethvin** [comment]
In any case it seems like a good idea to err on the side of caution and not change the code in 3.0. The ticket here is just to document that the easing functions get one argument.

**Comment by scottgonzalez** [comment]
> Even if only half of jQuery UI installs included UI effects core, that would still put easing over 9%.

Detection and overlaps are somewhat complicated. The two main methods are detecting URL patterns in `<script>` and detecting code patterns in script content. A large portion of jQuery UI users will just grab the entire suite from a CDN. In this case, BuiltWith probably doesn't parse the code since they already know that it points to jQuery UI. So even though many jQuery UI users will have the easing code, it wouldn't count as a hit for jQuery Easing. On the other hand, anyone who does a custom jQuery UI build and concatenates code, renames files, etc. would require code parsing. In this case, inclusion of jQuery UI could result in a hit for jQuery Easing in addition to a hit for jQuery UI.

Anyway, it sounds like it doesn't matter. So I guess this issue should be closed.

**Comment by AurelioDeRosa** [comment]
So, is the plan to document `jQuery.easing` with one argument and to document the version with four arguments but also specify that it's deprecated as of jQuery 3?

**Comment by markelog** [comment]
@dmethvin 

> In any case it seems like a good idea to err on the side of caution and not change the code in 3.0. The ticket here is just to document that the easing functions get one argument.

I'm sorry, i was under impression it was decided to put those arguments back, did i misunderstood.

@scottgonzalez 
> Anyway, it sounds like it doesn't matter.

That is all speculative, right? If there isn't any proof, i don't see how this numbers could be just thrown away.

@AurelioDeRosa 
> So, is the plan to document jQuery.easing with one argument and to document the version with four arguments but also specify that it's deprecated as of jQuery 3?

Idea was to just document it with one argument, we could mention that before it was different though

**Comment by markelog** [comment]
@dmethvin oooh, by 

> not change the code in 3.0

you probably meant to revert, right? I guess i did misunderstood :)

**Comment by dmethvin** [comment]
So I thought what we decided yesterday was to 1) put back the code for now that delivers the extra args to the easing functions, 2) deprecate them since they were undocumented, 3) document the single arg version in the entry for `.animate()`.

**Comment by markelog** [comment]
> 2) deprecate them since they were undocumented, 3) document the single arg version in the entry for .animate()

Yeah, although @timmywil suggestion was to just document one argument for `jQuery.easing` method, that way we would both document the object and deprecate those args.

It could be good to add a note of how it was before though.

**Comment by bharathirajauk** [comment]
animate method is throwing exception "TypeError: setting a property that has only a getter" using below code. 

 ```
 $ele.delay(delayInterval).each(function () { }).animate( 
             {
                    r: radius
                },   {
                    duration: 700,
                    step: function (now) {
                        scaleVal = now;
                     },
               }
       );
```

this is working fine in 2.1.4 version. If i refer 3.0.0 version, it throws above error.

JQuery3.0.0 source code: throws exception in the below set method
---------------------------------------------------------------------------
```
Tween.propHooks = {
      set: function( tween ) {
			if ( jQuery.fx.step[ tween.prop ] ) {
				jQuery.fx.step[ tween.prop ]( tween );
			} else if ( tween.elem.nodeType === 1 &&
				( tween.elem.style[ jQuery.cssProps[ tween.prop ] ] != null ||
					jQuery.cssHooks[ tween.prop ] ) ) {
				jQuery.style( tween.elem, tween.prop, tween.now + tween.unit );
			} else {
				tween.elem[ tween.prop ] = tween.now; // In this line throws above exception
			}
		}
}
```

**Comment by dmethvin** [comment]
@bharathirajauk This is the documentation repo. It appears you're trying to report a bug in the code, not the docs. Please report code bugs at https://github.com/jquery/jquery/issues and ***please include a working complete test case from jsbin.com or jsfiddle.net***.
