### ISSUE TITLE
jQuery.ajaxSettings.traditional

### ISSUE THREAD

**Issue by dmethvin** [jquery/api.jquery.com#919]
In http://api.jquery.com/jQuery.param/ we say that looking at the `traditional` flag was removed in 1.8 but in reality it didn't happen until 3.0. The note there needs to be updated to say 3.0.

**Comment by AurelioDeRosa** [comment]
So, I'd say that we should remove the note from master and add it in branch 3.

**Comment by dmethvin** [comment]
SGTM!
