### ISSUE TITLE
weird behavior from replaceWith by shorthand html tags

### ISSUE THREAD

**Issue by mafflerbach** [jquery/api.jquery.com#940]
actual:
it seems to be, that jquery handle the shorttags as an open tag and ignore the rest of content.
see file: 
[actual.txt](https://github.com/jquery/api.jquery.com/files/327325/actual.txt)

expected:
The behavior should be the same for `<tag></tag>` and `<tag/>`
[expected.txt](https://github.com/jquery/api.jquery.com/files/327326/expected.txt)

Test:
[test.txt](https://github.com/jquery/api.jquery.com/files/327311/test.txt)

**Comment by AurelioDeRosa** [comment]
Hi. Can you please create some [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) to demonstrate the issue?

**Comment by mafflerbach** [comment]
[https://jsbin.com/zategoyaso/edit?html,output](
https://jsbin.com/zategoyaso/edit?html,output)

normaly the expected output 

> Hey i replace
> 
> I replaced, too
> 
> Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.

but actual 

> Hey i replace

The rest of content is cutted

**Comment by AurelioDeRosa** [comment]
Your markup is invalid. The first `div` is self-closed which is incorrect. As soon as you fixed that issue, the code works correctly.
