### ISSUE TITLE
.data() api

### ISSUE THREAD

**Issue by feiwen8772** [jquery/api.jquery.com#943]
http://api.jquery.com/data/
 [the algorithm of the Dataset API](http://www.w3.org/TR/html5/dom.html#dom-dataset) 
not transforms URL

**Comment by feiwen8772** [comment]
![467d3ef5-cc98-46d6-a396-d998c0adbfce](https://cloud.githubusercontent.com/assets/373130/16515379/467659aa-3fa4-11e6-9f9f-16c1bf803ba9.png)

**Comment by mgol** [comment]
@AurelioDeRosa You need to run `npm version patch` and push the tag to the repo to trigger the page update, otherwise nothing happens.

**Comment by AurelioDeRosa** [comment]
Hey @mgol.

I knew it but usually I try to push a couple of changes before creating a new version.

**Comment by mgol** [comment]
Why? I don't see why it's necessary to wait for a week or two before a merged change gets published; I think we should do it immediately - the code is there, people should be able to see the updated site.

**Comment by AurelioDeRosa** [comment]
Well, I didn't write "wait for 1-2 weeks". I wrote "1-2 changes", which means merge 1-2 changes within 1-2 days and then push. If I forgot to push the change in one occasion, that's a different story.
