### ISSUE TITLE
delegate() is not listed as deprecated

### ISSUE THREAD

**Issue by teo1978** [jquery/api.jquery.com#945]
`.delegate()` isn't listed here:
http://api.jquery.com/category/deprecated/

nor is there any notice here: http://api.jquery.com/delegate/ saying that it is officially deprecated. It only says:
> As of jQuery 1.7, .delegate() has been superseded by the .on() method.

However, a search for the word "deprecated" in the page will find nothing.

Yet, if you use the jQuery 3 Migrate plugin, you will get warnings if you use `delegate()` that it is deprecated.

**Comment by markelog** [comment]
Nice catch! Would you like to send us a pr for that?
