### ISSUE TITLE
Deprecate jQuery.now docs changes

### ISSUE THREAD

**Issue by ShashankaNataraj** [jquery/api.jquery.com#947]
Raising this issue as per the PR checklist. There are docs changes involved with fixing:
https://github.com/jquery/jquery/issues/2959

**Comment by AurelioDeRosa** [comment]
Thank you for opening this. I'll document the deprecation as soon as version 3.2.0 will be released.

**Comment by AurelioDeRosa** [comment]
Thank you for opening this. I'll document the deprecation as soon as version 3.2.0 will be released.
