### ISSUE TITLE
Deprecate jQuery.isNumeric docs changes

### ISSUE THREAD

**Issue by ShashankaNataraj** [jquery/api.jquery.com#949]
Raising this issue as per the PR checklist. There are docs changes involved with fixing: https://github.com/jquery/jquery/issues/2960

**Comment by Schweinepriester** [comment]
+1

Mentioned in <https://blog.jquery.com/2018/01/19/jquery-3-3-0-a-fragrant-bouquet-of-deprecations-and-is-that-a-new-feature/> but not yet in the docs…
