### ISSUE TITLE
$ele.find(...) weirdly returns elements outside $ele if $ele have similar ID 

### ISSUE THREAD

**Issue by damhonglinh** [jquery/api.jquery.com#954]
When there are elements with the same ID (due to very-hard-to-change "old code"), `$ele.find('.label + span')` (Next Adjacent Selector is required to produce the bug -- due to very-hard-to-change "old code", again) returns `<span>` elements which are not descendants of `$ele`. The 2 keys to reproduce the bug is:
+ Outer elements have the same ID (which I know is bad).
+ The selector in the argument of `.find()` contains Next Adjacent Selector (which I know is also bad).

Example code (http://codepen.io/damhonglinh/pen/bZYzxm?editors=1011):
``` html
<div class='ele' id='id_'>
  <span class='label'>Label:</span>
  <span>Mango</span>
  <div class='placeholder'>placeholder</div>
</div>

<div class='ele' id='id_'>
  <span class='label'>Label:</span>
  <span>Lemon</span>
  <div class='placeholder'>placeholder</div>
</div>

<div class='ele' id='id_1'>
  <span class='label'>Label:</span>
  <span>Cherry</span>
  <div class='placeholder'>placeholder</div>
</div>

<button class='run-jquery'>Run jQuery</button>
<button class='run-zepto'>Run Zepto</button>

<script>
var run = function($) {
  $('.ele').each(function(index, ele) {
    var $ele = $(ele),
        text = $ele.find('.label + span').text(); // `text` here should be a fruit name, not all fruit names
    $ele.find('.placeholder').html(text);
  });
};

$('.run-jquery').click(function() { run($); });
$('.run-zepto').click(function() { run(Zepto); });
</script>
```

I tested this with Zepto and it doesn't have this bug though.

**Comment by gibson042** [comment]
Duplicate ids aren't just bad, they're [invalid](https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute):
> When specified on <a id="global-attributes:html-elements-5" href="https://html.spec.whatwg.org/multipage/infrastructure.html#html-elements">HTML elements</a>, the <code id="global-attributes:the-id-attribute-2"><a href="https://html.spec.whatwg.org/multipage/dom.html#the-id-attribute">id</a></code> attribute value must be unique amongst all the <a href="https://dom.spec.whatwg.org/#concept-id" id="global-attributes:concept-id" data-x-internal="concept-id">IDs</a> in the element's <a id="global-attributes:tree" href="https://dom.spec.whatwg.org/#concept-tree" data-x-internal="tree">tree</a> and must contain at least one character.

If you truly can't correct the source, then I recommend a post-selection filter:
```js
$ele.find(".label + span").filter(function( i, el ) {
	return $( el ).parents().is( $ele );
});
```

**Comment by damhonglinh** [comment]
Thanks for the recommendation although I used this approach `$ele.find(".label").next("span")`. Hopefully it will work expectedly.

**Comment by gibson042** [comment]
Only because of an optimization in simple selector handling. If you want reliable behavior, use my suggestion.
