### ISSUE TITLE
[jQuery.ajax about jsonp] error description for dataType and more explicit description for url

### ISSUE THREAD

**Issue by Aqours** [jquery/api.jquery.com#959]
URL: http://api.jquery.com/jQuery.ajax/
1. An error description for dataType
   ![qq 20160722102217](https://cloud.githubusercontent.com/assets/8586286/17044978/a7e9f9a4-4ff7-11e6-9ff6-49d90e24e900.png)
   Actually cross-domain `"json"` requests will be not converted to `"jsonp"`.
2. JavaScript code

``` javascript
// the url of current page is
// http://www.a.com
// then send a request
// http://www.b.com/search.php support jsonp
$.ajax({
    url: "http://www.b.com/search.php?callback=?",
    data: {
        // ...
    },
    dataType: "json"
});
```

This request will be auto converted to `"jsonp"`. Write this feature on jQuery document that will be good for users. I think this way is more useful than `dataType: "jsonp"` occasionally.

**Comment by dmethvin** [comment]
Doesn't your example show the documentation is correct?

**Comment by Aqours** [comment]
1. The wrong on jQuery document.
2.  Adds an extra `"?callback=?"` to the end of your URL to indicate that loads in a JSON block using JSONP when using `dataType: "json"` or `dataType: "jsonp"`. (I think it will be a more accurate description about my example)

**Comment by onebytegone** [comment]
I recently noted this issue as well. The section that is particularly confusing is listed below, please note bold italicized text.

> `"json"`: Evaluates the response as JSON and returns a JavaScript object. _**Cross-domain `"json"` requests are converted to `"jsonp"` unless the request includes `jsonp: false` in its request options.**_ The JSON data is parsed in a strict manner; any malformed JSON is rejected and a parse error is thrown. As of jQuery 1.9, an empty response is also rejected; the server should return a response of null or {} instead. (See json.org for more information on proper JSON formatting.)

From this section of the docs I would gather that, using the example that @Aqours gave, the following would result:

   1. The script loads on the domain of 'https://www.a.com' in a browser does not have CORS, e.g. IE9.
   2. An `ajax` request is made to a different domain using the `json` data type.

      ```js
      $.ajax({
         url: 'https://www.b.com/search.php',
         dataType: 'json'
      });
      ```

   3. jQuery appends a callback parameter to the url and makes the call via [the `script` transport](https://github.com/jquery/jquery/blob/1.11.0/src/ajax/script.js#L34-L91)
      - This assumption is based on the following:
         - The request is cross domain (`'https://www.b.com' !== 'https://www.a.com'`)
         - `'jsonp' !==  false` as the `jsonp` option defaults to `callback`
         - The `dataType` is `json` and according to "Cross-domain `"json"` requests are converted to `"jsonp"`" will be treated as JSONP

The above however does not occur, no callback is appended nor is the `<script>` transport used. In order for the request to be treated as JSONP, that of the url receiving a callback function and being request via the `script` tag transport, one of the following must happen:

```js
// Option 1: `callback=?` in url
$.ajax({
   url: 'https://www.b.com/search.php?callback=?',
   dataType: 'json'
});

// Option 2: `dataType` set to `jsonp`
$.ajax({
   url: 'https://www.b.com/search.php',
   dataType: 'jsonp'
});
```

In light of this, the following seems more accurate:

> `"json"`: Evaluates the response as JSON and returns a JavaScript object. Cross-domain `"json"` requests that have a callback placeholder, e.g. `?callback=?`, are performed using [JSONP](http://bob.ippoli.to/archives/2005/12/05/remote-json-jsonp/) unless the request includes `jsonp: false` in its request options. The JSON data is parsed in a strict manner; any malformed JSON is rejected and a parse error is thrown. As of jQuery 1.9, an empty response is also rejected; the server should return a response of null or {} instead. (See json.org for more information on proper JSON formatting.)

A more extensive set of examples of this behavior can be found at: https://github.com/onebytegone/jquery-ajax-jsonp

_Note:_ This behavior has been confirmed in jQuery v1.11.0, v1.12.4, v2.2.4, and v3.1.1.

**Comment by dmethvin** [comment]
This sounds like a very good clarification, can you submit a PR at https://github.com/jquery/api.jquery.com/?

The current docs are consistent in that `dataType` is about the type of the *received* data and it only mentions changing the URL when it does so itself. However, I can understand the confusion.

**Comment by AurelioDeRosa** [comment]
@dmethvin are you sure you wanted to close this issue?

**Comment by dmethvin** [comment]
Duh, no! I must have confused two tabs at the time. @onebytegone you are in the right place! 😕

**Comment by mgol** [comment]
@Aqours Why did you close it? Reopening.

**Comment by Aqours** [comment]
@mgol For a long time no one had dealt with this issue. Remain issue opened if you track it.

**Comment by mgol** [comment]
@Aqours All of the people working on this repo are volunteers and we have limited manpower so there are silent periods.
