### ISSUE TITLE
Documentation is wrong(http://api.jquery.com/jQuery/#jQuery-selector-context)

### ISSUE THREAD

**Issue by luisasalas** [jquery/api.jquery.com#965]
http://api.jquery.com/jQuery/#jQuery-selector-context

Documentation is wrong(http://api.jquery.com/jQuery/#jQuery-selector-context)
Context can be of Type: Element or jQuery or Selector not Type: Element or jQuery.

See source code.
https://github.com/jquery/jquery/blob/305f193aa57014dc7d8fa0739a3fefd47166cd44/src/core/init.js#L94

**Comment by timmywil** [comment]
It may work, but that doesn't mean it's supported and should be documented. Besides, if you're passing in a selector with a selector context, you may as well just pass a selector without a context.

**Comment by dmethvin** [comment]
I agree with @timmywil, it is not valid to trace the current code execution paths and declare that whatever they happen to do right now is what should be documented.
