### ISSUE TITLE
Serialize of a disabled form.

### ISSUE THREAD

**Issue by JakeCigar** [jquery/api.jquery.com#966]
3.1.0 returns an empty string in Chrome/Opera and IE. With older (1.x.x) jQuery or other browsers it works fine.

 Safari, and Firefox seem fine.
[ser.html.zip](https://github.com/jquery/api.jquery.com/files/404741/ser.html.zip)

**Comment by dmethvin** [comment]
Hey @JakeCigar this sounds like a potential code bug and not a docs bug. I don't think forms have a `disabled` attribute. Can you file a bug report at the jquery code repo?

**Comment by JakeCigar** [comment]
Sorry about that… hit the wrong bug reporter.
