### ISSUE TITLE
unbind accepts several event types

### ISSUE THREAD

**Issue by PhiLhoSoft** [jquery/api.jquery.com#975]
I read the [`unbind`](http://api.jquery.com/unbind/) documentation. I use `unbind` instead of `off`, because I work on a legacy project.
Anyway, I see the [`bind`](http://api.jquery.com/bind/) doc defines `eventType` as "_A string containing one or more DOM event types_", while `unbind` defines it as "_A string containing a JavaScript event type_".
So it is unclear if we can specify several event types in `unbind`.
I tried the example of the page, adding `mouseenter` to `click`, and it worked.
So I suggest to update the doc to reflect this fact. Or to openly discourage this practice, if it is frowned upon... (but parameterless `unbind` is "worse", so...)

Note: previously reported at https://github.com/jquery/jquery.com/issues/146

**Comment by AurelioDeRosa** [comment]
The issue reported is correct. I'm going to submit a PR to address it.
