### ISSUE TITLE
Document that innerWidth/OuterWidth are now setters as well

### ISSUE THREAD

**Issue by mikesherov** [jquery/api.jquery.com#98]
usage:

`innerWidth(number)` will subtract the padding, in pixels from number, and set the css width of the element to the difference

`outerWidth(number)` will subtract the padding and border, in pixels from number, and set the css width of the element to the difference

`outerWidth(number, true)` will subtract the padding and border and margin, in pixels from number, and set the css width of the element to the difference

**Comment by arthurvr** [comment]
outerHeight is the only one that doesn't have this signature yet.
