### ISSUE TITLE
.clone() documentation incorrectly states a parameter's default value

### ISSUE THREAD

**Issue by azuredusk10** [jquery/api.jquery.com#980]
Hello,

I've been learning how to use the .clone() method.
https://api.jquery.com/clone/

On the documentation it states that the 2nd parameter, _deepWithDataAndEvents_, by default inherits the value you pass as the 1st parameter, _withDataAndEvents_. However, through experimenting with this method, this doesn't seem to be the case. The 2nd parameter just seems to default to false unless you explicitly set it as true.

**Comment by AurelioDeRosa** [comment]
As you can see [from the source](https://github.com/jquery/jquery/blob/2d4f53416e5f74fa98e0c1d66b6f3c285a12f0ce/src/manipulation.js#L393):

```js
deepDataAndEvents = deepDataAndEvents == null ? dataAndEvents : deepDataAndEvents;
```

if no value is passed for `deepDataAndEvents`, the value of `dataAndEvents` is used.

I'm closing this issue for now. If someone disagrees with me, feel free to open again.
