### ISSUE TITLE
.val() documentation should mention radio buttons

### ISSUE THREAD

**Issue by Chealer** [jquery/api.jquery.com#981]
http://api.jquery.com/val/ contains:

> For selects and checkboxes, you can also use the :selected and :checked selectors to get at values. For example:
>  
> // Get the value from a dropdown select
> $( "select.foo option:selected").val();
>  
> // Get the value from a dropdown select even easier
> $( "select.foo" ).val();
>  
> // Get the value from a checked checkbox
> $( "input:checkbox:checked" ).val();
>  
> // Get the value from a set of radio buttons
> $( "input:radio[name=bar]:checked" ).val();

Since the example covers radio buttons, the description should read:

> For selects, checkboxes and radio buttons, you can also use the :selected and :checked selectors to get at values.

**Comment by gibson042** [comment]
I agree about the mention of radio inputs, and would also like to see some other cleanup there:
* Replace all use of nonstandard `:selected` with standard `:checked`
* Replace nonstandard `:checkbox` with `[type=checkbox]`
* Replace nonstandard `:radio` with `[type=radio]`

@Chealer would you like to submit a pull request?

**Comment by Chealer** [comment]
Commit 61ffc08636ed39b17d828e6406d63631c3f29ade solves the issue I reported.

**Comment by mgol** [comment]
I extracted @gibson042's proposals into #993 as the PR #987 covered just the initially reported issue.
