### ISSUE TITLE
Documentation does not make it clear that removed methods are gone

### ISSUE THREAD

**Issue by jribbens** [jquery/api.jquery.com#984]
I spent some time chasing down a bug whereby using the `.load()` event-handler did not work. It turned out that this method has been removed in jQuery 3.0.

I realise that many people are not using the latest versions of jQuery and therefore the documentation has to cater for them. However usually it is expected that the latest documentation documents the latest version primarily, and the documentation for this very significant change (i.e. method removed completely) is very subtle (small writing way off to the side).

I would suggest that perhaps in the API index, methods that have been removed should be greyed out in some way, so people can still find them if using old jQuery versions but it's obvious they're gone or going, and the detail page for the method should have a **very prominent** (e.g. a big red full-width banner) warning that the function no longer exists in the latest version.

**Comment by dmethvin** [comment]
I agree, this is already in #971. If you'd like to work on it please let us know!
