### ISSUE TITLE
.outerHeight( function(index, height) ) doesn't specify the function prototype

### ISSUE THREAD

**Issue by tdelmas** [jquery/api.jquery.com#989]
https://api.jquery.com/outerheight/#outerHeight-functionindex--height specify only
`Type: Function()`
https://api.jquery.com/innerheight/#innerHeight-function is more specific:
`Type: Function( Integer index, Number height ) => String or Number`
I think for outerHeight it should be the same?

**Comment by AurelioDeRosa** [comment]
Thank you for opening this issue. I'll fix this ASAP.
