### ISSUE TITLE
jQuery.map() is a lie

### ISSUE THREAD

**Issue by sxlijin** [jquery/api.jquery.com#990]
`map` functions generally do not (in my experience, frankly, never) flatten their return by default. I can understand the devs being concerned about library stability and not wanting to change this, since the behavior has been this way for so long, but at the very least, this behavior should be **clearly and explicitly documented at the top of the page** to make it clear that the behavior of `$.map` is non-standard.

[Here is the relevant doc page](http://api.jquery.com/jquery.map/), a [ticket opened 5 years ago questioning this behavior](https://bugs.jquery.com/ticket/10541) and a [SO answer](http://stackoverflow.com/questions/703355/is-there-a-jquery-map-utility-that-doesnt-automically-flatten) explaining how to work around this.

Obnoxiously busy right now, otherwise I'd PR it myself.

**Comment by dmethvin** [comment]
The documentation for both [jQuery.map()](http://api.jquery.com/jquery.map/) seems pretty clear about this behavior already. There aren't that many words there, I'm not sure how they would be rearranged to make it clearer but you're welcome to submit a PR that has a non-accusatory tone and we'll consider it. In the meantime I'll close this ticket, but again if you feel like you can improve the docs please do submit a PR.

**Comment by sxlijin** [comment]
Sorry about the tone! Meant the title as more of a "the cake is a lie"-esque attitude.
