### ISSUE TITLE
Query add wrong element for table

### ISSUE THREAD

**Issue by gatksun** [jquery/api.jquery.com#995]
I tried to add new element : table, but JQuery did wrong.
<div id="mainbox"></div>
I tested javascript:
$('#mainbox').add('table').attr('id','maintable');
I find $('#maintable')[0].tagName is not "TABLE", but it is "DIV".
IF I used $('#mainbox').add('<table id="mountable"></table>'), it would merge table if existing another table whose id is not same.
I do not know if my script is correct. Expect anyone to correct. Thanks, Howard

**Comment by dmethvin** [comment]
This is a jQuery usage question, best to ask it on StackOverflow.
